### ISSUE TITLE
API changed

### ISSUE THREAD

**Issue by jenhek** [gabstopper/smc-python#10]
After a while I knwo want to work further with the API.
Upgraded smc_python to 5.8.0
My simplex test  already fails at the import statement.

-----------------------------------------------
jens@halo 13:33:49 ~/smc-api> python3 test-smc-api.py 
Traceback (most recent call last):
  File "test-smc-api.py", line 8, in <module>
    from smc import session
ImportError: cannot import name 'session'

**Comment by jenhek** [comment]
Alright. Some has scrambled the permissions in our python installation :-(

Close this one.

**Comment by gabstopper** [comment]
Hi there, no problem! Note that the master branch now holds the dev releases. Pip now has the released version (all dev branch commits are also tested so still considered stable).
