### ISSUE TITLE
whitespace and dash sign in href causes error

### ISSUE THREAD

**Issue by sonicblind** [gabstopper/smc-python#11]
hi.

First of all I must say this library is excellent, thanks a lot! :-)

However I recently ran into a problem.
I am not sure whether it is a problem in smc-python or in the actual API implementation.

I found out that if a Host object has a name which contains white space character followed by dash, I cannot retrieve this object anymore with Host('name'), while I can still retrieve it with Host.objects.all().

The problematic name is for example: "h_name - test", while something like "h_name- test" works fine.
So it looks to be really just the case of special character combination "% -%".
I have no power to enforce the no-space naming convention among the firewall admins, so I have to cope with it somehow.

When I want to create a new group object with a host object having this weird name...
Group.create('group_name', members) where 'members' is a list containing elements like Host('name')
I receive an error that the Host object could not be found. So apparently Group.create is looking for the host object in the form of Host('name') but when the name has this problematic syntax, it fails to find it. Probably something with the URL encoding?

How could I work around this issue? THX

Here is the example code:
```
name='h_name- test'
print('OBJECTS ALL:')
for host in Host.objects.all():
	if host.name == name:
		print(host.name)
		print(host.href)
print('-----')

print('HOST Directly:')
host = Host(name)
print(host.name)
print(host.href)
```

And console output:
```
~/scripts/APIs$ ./test5.py 
OBJECTS ALL:
h_name - test
http://hostname:8082/5.10/elements/host/15157
-----
HOST Directly:
h_name - test
Traceback (most recent call last):
  File "./test5.py", line 51, in <module>
    print(host.href)
  File "/usr/local/lib/python3.6/dist-packages/smc_python-0.5.6-py3.6.egg/smc/base/model.py", line 202, in __get__
    instance.typeof))
smc.api.exceptions.ElementNotFound: Cannot find specified element: h_name - test, type: host

~/scripts/APIs$ ./test5.py 
OBJECTS ALL:
h_name- test
http://hostname:8082/5.10/elements/host/15157
-----
HOST Directly:
h_name- test
http://hostname:8082/5.10/elements/host/15157
```

**Comment by gabstopper** [comment]
Hi,
Thanks for the feedback! 
From your URL string it appears you are using the 5.10 version of the SMC API. Which version of the SMC are you currently running? I tried with SMC 6.3.4 using the 5.10 API and didn't see the same problem. Also, i'm wondering if you could run the following:

```
import smc
print(smc.__version__)
```

**Comment by sonicblind** [comment]
Hi.
Thanks for reply . Here is the requested info:

```
print("API VERSION: ", smc.__version__)
print("SYS VERSION: ", System().smc_version)

API VERSION:  0.5.6
SYS VERSION:  5.10.5 [10037]

```

Upgrading SMC at the moment is most probably not an option so I have to live with 5.10.5.
Do you think I can use different API version or do something else to work around this issue?

If not, then I would have to make the firewall admins fix all problematic object names and remove white spaces, but this is not future-proof solution.

**Comment by gabstopper** [comment]
Hi there,
I looked at this closer and it is indeed an issue with the SMC itself, not even the SMC API. For example, you can go into your SMC UI and View->Search and attempt to find the same host 'h_name - test' and it will not find the host after the first part of the name: 'h_name -'. 

The reason the Host.objects.all() works is because this fetch is done against the entry point 'host' which just returns a collection of all hosts (no filters).

Attempting to find a reasonable workaround.

**Comment by sonicblind** [comment]
Hi gabstopper,

You are right. It is the SMC itself, now I figured it out as well, based on your last message.
If you hover the mouse cursor over the search field in View->Search, it explains everything. 
SMC takes search string "host -test" as a specially crafted search string telling SMC to find objects with name starting with "host" but NOT including string "test".

So I created these test objects:
![image](https://user-images.githubusercontent.com/36238727/36021568-7e76719e-0d86-11e8-8240-01a743faf57d.png)

And following screenshots explain the search behavior:

This one is simple and clear:
![image](https://user-images.githubusercontent.com/36238727/36021739-0681fd6a-0d87-11e8-9e4c-b5644b0d35e8.png)

This one finds anything which starts with "h_example" but does not contain "test":
![image](https://user-images.githubusercontent.com/36238727/36021754-15875df0-0d87-11e8-9b7e-1752f674d08d.png)

This one finds nothing but I am not sure how to interpret it, because if it should mean find anything which starts with "h_example" but does not contain whitespace, then it should find the first object "h_example". but probably the "test" at the end of the search string does also something else:
![image](https://user-images.githubusercontent.com/36238727/36021782-280e7d50-0d87-11e8-9f22-b1931fd7fb3d.png)

If I escape the minus sign, it actually finds exactly what I would expect:
![image](https://user-images.githubusercontent.com/36238727/36021794-32e859c6-0d87-11e8-8355-d2ade5dc21ef.png)

Unfortunately, escaping the minus sign in the code does not help, the API probably interprets it differently: 

```
HOST Directly:
h_example \- test
Traceback (most recent call last):
  File "./test5.py", line 52, in <module>
    print(host.href)
  File "/usr/local/lib/python3.6/dist-packages/smc_python-0.5.6-py3.6.egg/smc/base/model.py", line 202, in __get__
    instance.typeof))
smc.api.exceptions.ElementNotFound: Cannot find specified element: h_example \- test, type: host
```

Funny enough, I never used this kind of SMC UI search in View->Search.
I always search objects directly in the object view by just simply start typing the search string. 
But here the search works differently - it takes my search string literally and finds the problematic object correctly:

![image](https://user-images.githubusercontent.com/36238727/36022243-a905f158-0d88-11e8-87f1-b16b757cc287.png)

To me it looks like there is no way to workaround this issue in the code itself - when the escaping does not help. I tried with backslashes, %20, or even \s. Non of these worked.
But if you find any solution it would be perfect :-)

**Comment by gabstopper** [comment]
Hi there,
I have a workaround that should work for this issue. You can add this to the top of your script to replace the default descriptor for the Element class.
Basically this will use the same logic to retrieve the element, but if the element has a '-' in it, it will split on '-' and do a non-exact match on the left most value. This will/could return multiple results so it will then check the results and return only the exact match or raise ElementNotFound exception. 

Please give this a try and let me know if that works. I will incorporate this into the native lib as well for next push.

```
from smc.api.common import fetch_href_by_name
from smc.base.util import unicode_to_bytes
from smc.base.model import Meta
from smc.api.exceptions import ElementNotFound

class MyElementLocator(object):
    """
    There are two ways to get an elements location, either through
    collections which returns the instance type with the populated
    meta attribute, or by loading the resource directly, i.e. Host('myhost').

    If the element is loaded directly, it should define a class attribute
    'typeof' to specify the element type. The 'typeof' attribute correlates
    to the SMC API entry point for the element. Classes deriving from
    :class:`Element` will define this attribute. When loading via
    Host('myhost'), you will have an empty instance as the cache is not
    hydrated until some action is called on it that accesses the instance
    property 'data'.
    Once hydrated, original json is stored in instance.data.

    Classes deriving from :class:`SubElement` do not have valid entry points in
    the SMC API and will be typically created through a reference link.

    This descriptor is a non data descriptor and can be overridden if 'href'
    is defined in the instance dict.
    """

    def __get__(self, instance, cls=None):
        # Does the instance already have meta data
        if instance._meta:
            return instance._meta.href
        else:
            if hasattr(instance, 'typeof'):
                if '-' in instance.name and not instance.name.startswith('-'):
                    name_parts = instance.name.split('-')
                    element = fetch_href_by_name(
                        name_parts[0],
                        filter_context=instance.typeof,
                        exact_match=False)
                    if element.json:
                        # Now return the exact match by original name
                        for result in element.json:
                            if result.get('name') == instance.name:
                                instance._meta = Meta(**result)
                                return instance._meta.href
                else:    
                    element = fetch_href_by_name(
                        instance.name,
                        filter_context=instance.typeof)
                    if element.json:
                        instance._meta = Meta(**element.json[0])
                        return instance._meta.href
                raise ElementNotFound(
                    'Cannot find specified element: {}, type: {}'
                    .format(unicode_to_bytes(instance.name),
                            instance.typeof))
            else:
                raise ElementNotFound(
                    'This class does not have the required attribute '
                    'and cannot be referenced directly, type: {}'
                    .format(instance))


Element.href = MyElementLocator()
```

**Comment by sonicblind** [comment]
Hi there,

It looks to be working perfectly, just as you described it. It's now part of my script, so far all good.
I will keep it there and shall it raise any errors I will let you know.
Thanks a lot for your quick help, much appreciated!
