### ISSUE TITLE
Unable to create TCP/UDP service object with min/max source port values

### ISSUE THREAD

**Issue by sonicblind** [gabstopper/smc-python#12]
Hi there,

I have another small issue.
I am trying to create a complex TCP service object with following parameters:
 - name
 - min and max source port values
 - min and max destination port values
 - protocol agent identifier

Something like this (made up example):

![image](https://user-images.githubusercontent.com/36238727/36162639-447bf7fc-10e7-11e8-9454-a1401a195974.png)

However it looks like smc-python provides only: name, min/max destination port and comment:

![image](https://user-images.githubusercontent.com/36238727/36162437-c27c6f48-10e6-11e8-94f9-0ff016f2e558.png)

Is there any way how to create new service objects at least additionally with source port values (protocol agent I can live without)?

Thanks!

**Comment by gabstopper** [comment]
Hi, 
Thanks for the request! You are correct, the min/max source ports are not in the constructor. I will add those for the next release. 
In the meantime, you can update an element at any time using valid attributes.
To see attributes of a particular element, you would fetch it, then print the 'data' attribute.

For the TCP/UDP services, you can add the source ports by doing:

```
tcp = TCPService.create(name='testport', min_dst_port=9000, max_dst_port=10000)
tcp.update(min_src_port=30000, max_src_port=35000)
```

You can also reload an existing element to modify directly by:
```
tcp = TCPService('testport')
tcp.update(min_src_port=30000, max_src_port=35000)
```

If you print any element's `data` attribute, you will see a list of the locally cached attributes for that element:

pprint(tcp.data)
```
{u'key': 609,
 u'link': [{u'href': u'http://xxx/6.4/elements/tcp_service/609',
            u'rel': u'self',
            u'type': u'tcp_service'},
           {u'href': u'http://xxx/6.4/elements/tcp_service/609/export',
            u'rel': u'export'},
           {u'href': u'http://xxx/6.4/elements/tcp_service/609/history',
            u'rel': u'history'},
           {u'href': u'http://xxx/6.4/elements/tcp_service/609/search_category_tags_from_element',
            u'rel': u'search_category_tags_from_element'},
           {u'href': u'http://xxx/6.4/elements/tcp_service/609/duplicate',
            u'rel': u'duplicate'}],
 u'max_dst_port': 10000,
 u'max_src_port': 35000,
 u'min_dst_port': 9000,
 u'min_src_port': 30000,
 u'name': u'testport',
 u'read_only': False,
 u'system': False}
```
To force an immediate update, you can call update(key=value, key2=value, etc).
Normally you shouldn't have to do this as the element classes are intended to provide a simplified interface to elements but there are also ways to sneak around those :)

**Comment by sonicblind** [comment]
This works like a charm, thanks a lot for quick response! It allows me to progress with my project ;-)
