### ISSUE TITLE
How to create rule section in FirewallPolicy?

### ISSUE THREAD

**Issue by sonicblind** [gabstopper/smc-python#13]
Hi,

Is there a way to ask SMC API to create a rule section rule in firewall or NAT policy?
To achieve something like this:

![image](https://user-images.githubusercontent.com/36238727/36281822-5ac51606-129f-11e8-80b5-c16e776f7223.png)

In XML config export it would be a combination of these tags:

```
<fw_policy>
    <access_entry>
        <rule_entry>
            <access_rule>
                ...
            </access_rule>
        </rule_entry>
        <rule_entry comment="Section Nr.1">
            <comment_rule/>
        </rule_entry>
        <rule_entry>
            <access_rule>
                ...
            </access_rule>
        </rule_entry>
    </access_entry>
</fw_policy>
```

When I print out all data of all 3 rules with rule.data there is nothing special, nothing different in the section rule which would suggest this is a section rule. Except that it has no source, destination, service, action defined. 

But if I try to create a new rule with the API and simply say:
policy.fw_ipv4_access_rules.create(name='Section Nr.1')
it only creates a new standard rule. I don't see a way to say I want the new rule to be rules section rule.

So is it even possible in any way?

Thanks.

**Comment by gabstopper** [comment]
Hi, I just took a look and indeed it looks possible. I will add to the standard library. Stand by and I will get you a temporary workaround as well!

**Comment by sonicblind** [comment]
Wow, can't wait to see how :-)

**Comment by gabstopper** [comment]
My apologies for the delay on this one. And I apologize for providing hacks for these also but where there is python, there is a way... This will be added to version 0.6.1 which will release shortly after 6.4 is released (should be in the next week). In the meantime, this is a pre-release patch that you could apply. In 0.6.1 this will not be required.

```
from smc.base.model import SubElementCreator
from smc.api.exceptions import CreateRuleFailed
from smc.policy.layer3 import FirewallPolicy
from smc.policy.rule import IPv4Rule
    
class RuleSection(IPv4Rule):
    pass
        
def create_rule_section(self, name, add_pos=None, after=None, before=None):
    """
    Create a rule section in a Firewall Policy. To specify a specific numbering
    position for the rule section, use the `add_pos` field. 
        
    :param str name: create a rule section by name
    :param int add_pos: position to insert the rule, starting with position 1.
        If the position value is greater than the number of rules, the rule is
        inserted at the bottom. If add_pos is not provided, rule is inserted in
        position 1. Mutually exclusive with ``after`` and ``before`` params. 
    :param str after: Rule tag to add this rule after. Mutually exclusive with
        ``add_pos`` and ``before`` params. 
    :param str before: Rule tag to add this rule before. Mutually exclusive with
        ``add_pos`` and ``after`` params. 
    :raises MissingRequiredInput: when options are specified the need additional  
        setting, i.e. use_vpn action requires a vpn policy be specified. 
    :raises CreateRuleFailed: rule creation failure 
    :return: the created ipv4 rule 
    :rtype: IPv4Rule 
    """
    section = RuleSection(href=self.get_relation('fw_ipv4_access_rules'))
    href = section.href
    params = None
    if add_pos is not None:
        href = section.add_at_position(add_pos)
    else: 
        params = section.add_before_after(before, after) 
        
    return SubElementCreator( 
        self.__class__, 
        CreateRuleFailed, 
        href=href, 
        params=params, 
        json={'comment': name}) 
```    

Now do the work:
```
# Grab your policy    
policy = FirewallPolicy('foopolicy')
    
# Search for the rule by name (or partial part of name) to find the
# rule where we want the rule section
rule = policy.search_rule('myrule')
if rule:
    # Use the rule TAG with 'before' or 'after' (mutually exclusive) to
    # specify the rule tag for placement
        
    # Add the rule section before the rule searched
    create_rule_section(policy, name='foo', before=rule[0].tag)
    # Add the rule after the rule searched
    create_rule_section(policy, name='foo', after=rule[0].tag)
    
# Instead if you want to add by rule position, you can use `add_pos`.
# If no position is specified, it is placed at the top.
create_rule_section(policy, name='foo', add_pos=5)
```

Note: this whakamole version will only work with FW access rules but in 0.6.1 it will be common to all rule types.

**Comment by sonicblind** [comment]
Hi there,

Thank you for this, it looks promising. I will implement it as the first thing tomorrow and let you know.

When you say, it works for access rules only at the moment, does it mean NAT rules are also out of scope until 0.6.1 is out?

By the way, I am struggling with two other small issues currently. Not sure if I should open a new thread but you tell me. Basically I am unable to:
- add a comment to rule. I can put some descriptive text into the name field, but this one I would prefer to keep for tag only, plus it has pretty strict length limitation. How could I add a comment to a rule? This is quite important feature to be missing.
- the ordering of rules is somehow weird. the API reference for add_pos states: "If the position value is greater than the number of rules, the rule is inserted at the bottom." I have my rules in an ordered list. So all I want is to add each new rule at the end of the policy. So I thought if I set add_pos to some really high number like 10000 or so, I can be pretty sure my new rule will always go at the end of the policy and I don't need to care about rule tags. In reality it works the opposite way, every rule goes at the beginning of the policy. What am I missing here?

Thanks for your help, much appreciated.

**Comment by gabstopper** [comment]
Hi,
This thread is ok to use. I just checked the rule logic and indeed it is missing the comment field. Not sure how that one slipped by but I will add it. I'm going to post a new version (before 0.6.1) on the latest branch that will incorporate these changes. 
In the meantime, I tested add_pos on the rule and in my tests it properly adds to the correct position. Do you have an example of a rule create that you could send me? This might be an old issue in the 0.5.6 API that you are currently using but I can confirm.

**Comment by gabstopper** [comment]
Ok. I've posted a new version that resolves several issues:
rule comments
tcp/udp service min/max source ports
create_rule_section on all rule types (including NAT)

You will have to keep the workaround provided in issue #11  for now as i'll resolve that in a different way in 0.6.1.

You can uninstall the 0.5.6 release and grab the latest dev release:
```
pip install git+https://github.com/gabstopper/smc-python.git
```

Example of using the rule sections:
```
policy = FirewallPolicy('mypolicy')
policy.fw_ipv4_access_rules.create_rule_section(name='attop')
# For NAT rules
policy.fw_ipv4_nat_rules.create_rule_section(name='mysection', add_pos=5)
```
I verified the `before` and `after` arguments to rules work, as does the add_pos option for the rules. Note that add_pos will treat a rule section as a rule also so you will need to account for that when inserting rules in or around a rule section.
Please let me know how that goes.

**Comment by sonicblind** [comment]
Hi David,

I have installed your dev release and everything works like a charm. So nice really! Thanks a lot for all your efforts! 

- rule comments work!
- min/max src ports inside service.create work!
- rule sections work!
- rule ordering with add_pos now also works as expected

I am staring at my screen, watching how new rules are showing up in SMC automatically, without any issues, finally after weeks of work I am done with my project to automatically migrate Juniper SRX firewall rules and required objects to SMC without creating duplicates, etc.

But I will definitely go on with something else SMC API related.

Thanks once again! :-)
