### ISSUE TITLE
Missing / Unpassable `comment` argument

### ISSUE THREAD

**Issue by stdedos** [gabstopper/smc-python#17]
https://github.com/gabstopper/smc-python/blob/9010c283e1632a05113bd82208f3023434b48865/smc/core/collection.py#L383

Missing, whereas it should be there?

https://github.com/gabstopper/smc-python/blob/9010c283e1632a05113bd82208f3023434b48865/smc/core/collection.py#L265

Passing `**kwargs` with `{'comment': 'ISP #1 IPv6'}` returns empty comment on the SMC

**Comment by gabstopper** [comment]
Hi Ntentos,
I tested both functions and it appears the comment is there, for the tunnel interface, it will be placed on the top level:

```python
engine.tunnel_interface.add_layer3_interface(interface_id='2034',
            address='34.34.34.34', network_value='34.34.34.0/24', zone_ref='voodoo', comment='mycomment')

However functionality is slightly different in the method where a VLAN is created. In this case, the comment is placed on the VLAN level and not the top level physical interface:

```python
engine.physical_interface.add_layer3_vlan_interface(interface_id=60,
    vlan_id=1, address='60.60.60.1', network_value='60.60.60.0/24',
    comment='some comment')
```
Maybe that is what you're seeing?

**Comment by stdedos** [comment]
Probably my most cryptic issue report yet 😝

I am adding VLANs to a Master Cluster's interfaces, and then I assign
IPv4/6 addresses to the VEs.

Neither Master's VLANs, nor IFs, nor IPs get the comment.

Disclaimers:
a) I had much trouble learning the ropes on how to do this. It is possible
that I have combined limited SMC API experience together with Pythonic
un-familarity.

b) Environment is a bit pre-configured, thus I have limited replayability.

**Comment by gabstopper** [comment]
Aha, I see now 😄. Ok, I did find that the comment on the interface when creating the virtual engine node was not being passed and therefore not set. Thanks for catching that. This also helped me identify another small issue with how the virtual engine was being nested on the VLAN of the master engine (I recently rewrote the interface backend). Those have been addressed in the latest master branch which will eventually (i.e. soon) be packaged for pip as version 0.7.0.

To get the latest master branch, remove the existing version and pull the latest.

Here is a short 'how to' that might help make some sense of the process of creating master engine interfaces and VE's:

For master engine and virtual engines, the first step is to get the master engine (assuming it's already been created):
```python
engine = Engine('api-master')
```
Create a virtual resource to be assigned to the master engine interface
The `vfw_id` is a unique identifier for the virtual resource:
```python
virtual_resource = engine.virtual_resource.create(name='resource1', vfw_id=0, comment='My virtual network1')
```
Then create the re-usable generic top level interface on the master engine:
```python 
engine.physical_interface.add(10, comment='toplevelcomment')
```

Add a VLAN only interface along with a virtual resource mapping. Virtual mapping value
is the interface ID the virtual engine will see. Using a specific VLAN per VE seems to be a common configuration from my experience.
```python
engine.physical_interface.add_layer3_vlan_interface(interface_id=10,
    vlan_id=1, virtual_mapping=0, virtual_resource_name='resource1', comment='my resource1')
```
And lastly, create the virtual engine. Note that the virtual engine interface ID maps to the `virtual_mapping` value created for the vlan interface above:
```python
from smc.core.engines import Layer3VirtualEngine
engine = Layer3VirtualEngine.create(
    name='layer3-resource',
    master_engine='api-master',
    virtual_resource='resource1',
    interfaces=[{'interface_id': 0,
                 'address': '1.1.1.1',
                 'network_value': '1.1.1.0/24',
                 'comment': 'virtual resource interface'}])
```
All of these should come equipped with your comments:

![image](https://user-images.githubusercontent.com/14811349/39219050-d02d1636-47ed-11e8-9c84-4f333f7cc67b.png)

Then VE:

![image](https://user-images.githubusercontent.com/14811349/39219060-e093d0be-47ed-11e8-80f9-fb123769ac58.png)

**Comment by stdedos** [comment]
Thank you. I will pull soon to test the results.

In the meantime, your how-to could deserve a Wiki Page, and/or example script. 😸

**Comment by stdedos** [comment]
I do see comments coming in, so I think newest commit works. I am rolling back to `0.6.0` due to other issues faced.

**Comment by gabstopper** [comment]
Ok. I saw your other issues, investigating now. I'll close this as resolved in latest build and address the others for upcoming release.
