### ISSUE TITLE
Multiple "Control Backup" interfaces

### ISSUE THREAD

**Issue by sebbbastien** [gabstopper/smc-python#2]
Hi,

It is possible to define multiple interfaces as "Control Backup":
![image](https://cloud.githubusercontent.com/assets/5331611/25315394/974bd654-2854-11e7-96bc-631f0fdcad17.png)

I don't know if this check should be done by the SMC, by APIs, or by me...

Best regards,

**Comment by gabstopper** [comment]
Hi,
Thanks for this - I think this should be validation done on the SMC API side but am verifying currently with the API dev team. This is a quick workaround that you can implement on the client side. I will implement this in smc-python as a function check for next commit. I think I will add helper methods at the interface level to 'set_as_backup_mgt()' and similar to encapsulate having to set the attributes directly, and then also allows for validation beforehand.

```python
engine = Engine('vm')
def has_control_backup(engine):
    for intf in engine.interface.all():
        for sub_interface in intf.sub_interfaces():
            if sub_interface.backup_mgt:
                return True
            break
    return False
    
if not has_control_backup(engine):
    intf = engine.interface.get(2)
    for sub_interface in intf.sub_interfaces():
        sub_interface.backup_mgt = True
    intf.save()
```

**Comment by gabstopper** [comment]
I have also just added **kw to interface constructors that allow you to enable sub interface level settings when creating the interface as well. For example, to create a new cluster interface, you would do:

```python
engine = Engine('vm')
engine.physical_interface.add_cluster_virtual_interface(
    interface_id=1, 
    cluster_virtual='6.6.6.1', 
    cluster_mask='6.6.6.0/24', 
    macaddress='02:03:03:03:03:02', 
    nodes=[{'address':'6.6.6.2', 'network_value':'6.6.6.0/24', 'nodeid':1}, 
                  {'address':'6.6.6.3', 'network_value':'6.6.6.0/24', 'nodeid':2}],
    backup_mgt=True)     # <--- sub interface kwargs
```
This will be more efficient if you've already identified which interfaces you want to set as control backup interfaces at create time.

**Comment by sebbbastien** [comment]
Hi,

I got this error:
```
Traceback (most recent call last):
  File "auto-conf.py", line 152, in <module>
    backup_mgt=True)
TypeError: add_cluster_virtual_interface() got an unexpected keyword argument 'backup_mgt'
```

```
↪ pip show smc-python
Name: smc-python
Version: 0.5.1
Summary: Python based API to Stonesoft Security Management Center
Home-page: http://github.com/gabstopper/smc-python
Author: David LePage
Author-email: dwlepage70@gmail.com
License: Apache 2.0
Location: /usr/lib/python3.6/site-packages
Requires: requests
```

Do you commit your changes to Githb?
[interfaces.py](https://github.com/gabstopper/smc-python/blob/d557817ef504c5e1a5c3f8178641f820010e7194/smc/core/interfaces.py#L399)

```python
    def add_cluster_virtual_interface(self, tunnel_id, cluster_virtual=None,
                                      cluster_mask=None, nodes=None,
                                      zone_ref=None):
```

**Comment by gabstopper** [comment]
Hi, I have just committed 24cca4c with the changes. I have additional ones coming as well to simplify interface setting manipulation, for example, you will see new a 'set_primary_mgt()' method on engine.physical_interface. I am also moving forward the backup_mgt and other settings as well so you are forced to manipulate at the sub-interface level.

**Comment by sebbbastien** [comment]
Hi,

It works, thank you !
