### ISSUE TITLE
Adding Router to Interface places an IPv4 router to IPv6

### ISSUE THREAD

**Issue by stdedos** [gabstopper/smc-python#22]
After having (definitely) called:

```python
vfw.virtual_physical_interface.add_layer3_interface(*args, **kwargs)
```

I call:

```python
vfw.routing.get(if_id).add_static_route(Router(ROUTER_NAME.format(if_id, vfw.name.upper(), ipv)),
                                                        [Network('Any network')])
```

---

However, instead of neatly placing the elements (IPv4 router under the IPv4 network, same with IPv6), I get:

![image](https://user-images.githubusercontent.com/133706/39317552-8851d73c-4984-11e8-8efa-395e8e614289.png)

Notice that:
* first cloud (`7::/64`) has no child elements
* IPv4 router (`.1.2`) has Network segment, and
* IPv6 Router has a red icon, in addition to no Network Segment (apart from its name)

**Comment by gabstopper** [comment]
This would make sense since ipv6 isn't implemented on the routing node - or at least I was skipping IPv6 networks so not specifying a specific network/cidr would result in the Router being added to all networks including ipv6 networks even if it had only an ipv4 network address.
I am implementing ipv6 for the routing node now which should fix this issue. 
In the meantime if your router should only be on an ipv4 network, you could add like:
```python
ve.routing.get(0).add_static_route(Router('myipv4'), [Network('Any network')], network='1.1.1.0/24')
```
Another possible option would be to add a ipv6 address and ipv4 address to the router you are adding and skip the `network=` parameter. This should make it valid on both networks under interface 1.
Nonetheless, I'll have a fix and update for this issue.

**Comment by stdedos** [comment]
Following the precedent set on previous environments, I've used separate elements for IPv4 and IPv6.

> This would make sense since ipv6 isn't implemented on the routing node - or at least I was skipping IPv6 networks so not specifying a specific network/cidr would result in the Router being added to all networks including ipv6 networks even if it had only an ipv4 network address.

I am perplexed by the sentence structure - but I think you fuzzy-select by matching networks and/or you skip IPv6... Or I've messed up IPv6 Network & Router (and hence they don't match).

I'll try forcing a `network` key (because I don't think I've used it) and take it from there.
I'll try to update here sooner or later

**Comment by gabstopper** [comment]
You are correct on the matching - IPv6 networks are skipped when adding the gateway, but that will be modified for the next commit.

**Comment by gabstopper** [comment]
Please try the latest commit, IPv6 addresses should now be handled on routing nodes.

**Comment by stdedos** [comment]
There seems to be issues with IPv6 Routing (completely misses the IPv6 Router). Netlinks are also crippled (addition, matching, pairing-with provided network)

IPv4 Routing goes well with the new commit :smile:

**Comment by gabstopper** [comment]
This seems to test ok for me. One thing to note is that when you add a routing gateway to an interface that has an IPv6 address (and optionally also an IPv4 address), the routing gateway being added must also have an IPv6 address. This rule is "soft" in the sense that elements like an OSPF area or BGP Peering will be added regardless as they do not have associated addresses. 

So what this means is that if you attempt to add a static route (for example) on an interface that has both an IPv4 and IPv6 address and the "next hop" router element only has an IPv4 address, then the element will only be added to the IPv4 network. To add to the IPv6 network you must use a gateway element that has an IPv6 address or both IPv4 and IPv6 address.

For example:
```python
from smc.elements.network import Router
engine = Engine('layer3-resource')
itf = engine.interface.get(0)
print(list(itf.addresses))

[(u'2001:db8:85a3::8a2e:370:7334', u'2001:db8:85a3::/64', u'0'), (u'1.1.1.1', u'1.1.1.0/24', u'0')] #<- interface 0 has both an IPv6 and IPv4
```
Now add the static route. The Router "next hop" only has an IPv6 address assigned and will therefore only be placed on the IPv6 network of interface 0:
```python
rtitf0 = engine.routing.get(0)
rtitf0.add_static_route(Router('ipv6router'), [Network('Any network')])
```

Optionally if your Router element has both an ipv4 and ipv6 address and the destination in the route also has both ipv4 and ipv6, it will be added to both networks on that interface:
```python
rtr = Router('_myrouter')
print(rtr.address, rtr.ipv6_address)

(u'1.1.1.1', u'2001:db8:85a3::8a2e:370:7335') #<- router has both ipv4 and ipv6
```
Then add to interface 0 will bind to both:
```python
rtitf0 = engine.routing.get(0)
rtitf0.add_static_route(Router('_myrouter'), [Network('Any network')])
```

**Comment by stdedos** [comment]
It seems that this works correctly for me right now.

Have you pushed the changes sometime in-between?

**Comment by gabstopper** [comment]
Sorry for the delay on this; I didn't realize this was last replied to in July! I did address IPv6 issues back in April but mostly focused around IPv6 addressing being ignored in the routing assignments. Anyways, glad it is working, i'll close this out.
