### ISSUE TITLE
Interface rework + `add_layer3_interface`

### ISSUE THREAD

**Issue by stdedos** [gabstopper/smc-python#23]
_I believe to have this reported earlier, but I cannot find it! Let's go again_

After the Interface rework, PyCharm shows 2 interesting things:
![image](https://user-images.githubusercontent.com/133706/39369706-a7fbafce-4a45-11e8-9a32-0e327177d7bf.png)

`intf` (`for intf in vfw.virtual_physical_interface.all()`) is shown as to "possess" this attribute, whereas `vfw.virtual_physical_interface` shows as non-resolving.

I am not sure how easy or feasible is to get this fixed. Use best judgement :smile:

**Comment by gabstopper** [comment]
It appears PyCharm is introspecting the rtype of the method docstring (smc.core.engine.virtual_physical_interface) in which case it is correct - the rtype was InterfaceCollection. I've modified this to return VirtualPhysicalInterfaceCollection instead. Will be addressed in next post (along with the routing update).

**Comment by gabstopper** [comment]
Latest commit addresses the rtype docstring, please let me know if that resolves the issue!

**Comment by stdedos** [comment]
Resolves loudly and clearly :stuck_out_tongue_closed_eyes:
