### ISSUE TITLE
Differenciate dev-build version

### ISSUE THREAD

**Issue by stdedos** [gabstopper/smc-python#24]
... for easier traceability.

https://github.com/pyfidelity/setuptools-git-version

**Comment by stdedos** [comment]
Remember to generate docs for both versions :smiley:

**Comment by gabstopper** [comment]
Ok, develop branch has been added. The master branch will now be considered the primary / released version of code and should always be in sync with the pypi package. The develop branch will have a tag for each 'rc' version pushed for the next version, for example, the current develop branch now has 0.6.2.rc.1. 
Documentation is also synchronized with readthedocs so the branch will also have the latest up to date docs.
