### ISSUE TITLE
README updates

### ISSUE THREAD

**Issue by stdedos** [gabstopper/smc-python#28]
https://github.com/gabstopper/smc-python/blob/master/README.rst#67
>The master branch is used as a dev branch, installing from this branch will pull the latest code commit. All commits are still tested before being uploaded.

I guess you've changed that logic since #24?

**Comment by gabstopper** [comment]
Yes correct. I had to make a push to smc-python master branch before creating the develop branch so master is currently out of sync with the pip package. I'll be rolling a new release here soon to bring them back in sync (there were a couple issues during the split to develop branch).

**Comment by stdedos** [comment]
I am not sure if
`pip install smc-python>=0.6.2.rc1`
is supported, but
`pip install git+https://github.com/gabstopper/smc-python.git@develop`
is.

You can also add this information there

**Comment by gabstopper** [comment]
Resolved in 0.6.2.rc.2
