### ISSUE TITLE
Static routes

### ISSUE THREAD

**Issue by sebbbastien** [gabstopper/smc-python#3]
Hi,

Adding static-routes on the SMC can be done with Groups:
![image](https://cloud.githubusercontent.com/assets/5331611/25596515/c785700c-2ec9-11e7-9e6d-d5ca437910f8.png)

Is it possible to do the same way with API ?

It seems that static routes don't use the objects but IPs addresses: http://smc-python.readthedocs.io/en/stable/pages/engine.html?highlight=add_route#routing

Have a good day!

**Comment by gabstopper** [comment]
Ah yes - there is a helper method to add static routes by IP networks, but not directly via objects. I will add that to the routing configuration and update this evening.

**Comment by gabstopper** [comment]
Hi, you can now use the same routing node to add a static route with nested destination networks. You can also add additional if more are needed after initial adding:
```
>>> engine = Engine('ve-1')
>>> itf = engine.routing.get(0)
>>> itf.add_static_route(
            gateway=Router('tmprouter'),
            destination=[Group('routegroup')])
```
See http://smc-python.readthedocs.io/en/latest/pages/reference.html#smc.core.route.Routing.add_static_route

Please let me know how that works. Also there are new methods on the interface to move primary mgt, heartbeats, etc and moving interface ID's. Also adding change IP and VLAN options soon to come (abstracting away from of the lower level sub interface details).

**Comment by sebbbastien** [comment]
Hi,

Thank you for your update.

These routes where added with the API:
![image](https://cloud.githubusercontent.com/assets/5331611/25640905/d24fcdca-2f91-11e7-85c4-8ec225600be2.png)


Tanks a lot!
