### ISSUE TITLE
SMC_ADDRESS Environment variable doesnt work

### ISSUE THREAD

**Issue by darrenfp** [gabstopper/smc-python#31]
Hi David,

The issue is in the function `load_from_environ()` in [api/configloader.py ](https://github.com/gabstopper/smc-python/blob/master/smc/api/configloader.py#L70). The function `urlparse` must have changed as `url.hostname` no longer exists. 

I've added some debugging to highlight this issue.

```export SMC_ADDRESS=http://1.1.1.1:8082```

```python
url = urlparse(smc_address)

// debug statements
print("url: {}".format(url))
print("smc_address: {}".format(smc_address))
    
config_dict.update(smc_address=url.hostname) // non-existent value
```
```
// outputs in my console
url: ParseResult(scheme='http', netloc='1.1.1.1:8082', path='', params='', query='', fragment='')
smc_address: http://1.1.1.1:8082
```

I've a partial fix on my own machine; but I was wondering how you want this implemented. Happy to make a PR with a fix for this. I'm unsure as to what value `config_dict.update()` is expecting? Does it want the scheme & port, or just the domain/IP address?

**Comment by darrenfp** [comment]
Thanks David.

I'm still experiencing an issue with smc-python reading in `SMC_ADDRESS`.

```config_dict.update(smc_address=url.hostname) // url.hostname is non-existent```

Are you able to reproduce this?

**Comment by gabstopper** [comment]
Strange - I cannot reproduce. I have tried with python 2.7 and 3.5.1. What version do you currently use? So using the os.environ steps above didn't work for you? It might be related to urlparse - can you try this:

    import urlparse
    parsed = urlparse.urlparse('http://172.18.1.151:8082')
    print(parsed)
    print(parsed.hostname)
    print(parsed.scheme)
    print(parsed.port)

On my system with py2.7:

    ParseResult(scheme='http', netloc='172.18.1.151:8082', path='', params='', query='', fragment='')
    172.18.1.151
    http
    8082

**Comment by darrenfp** [comment]
The above code works in Python 2.7, but we're using 3.6 in our environment.

```bash
darren@dev:~/code/polaris-fwaas$ /usr/bin/python3.6 /home/darren/code/smc-test.py
Traceback (most recent call last):
  File "/home/darren/code/smc-test.py", line 1, in <module>
    import urlparse
ModuleNotFoundError: No module named 'urlparse'
darren@dev:~/code/polaris-fwaas$ /usr/bin/python /home/darren/code/smc-test.py
ParseResult(scheme='http', netloc='172.18.1.151:8082', path='', params='', query='', fragment='')
172.18.1.151
http
8082
darren@dev:~/code/polaris-fwaas$ cd ~/code
darren@dev:~/code$ python --version
Python 2.7.15rc1
darren@dev:~/code$ python3 --version
Python 3.6.5
```

**Comment by jpenttinen** [comment]
It looks that urlparse is renamed to urllib.parse

See https://bugs.launchpad.net/openstack-ansible/+bug/1712546
  
Page contains following tip (should be Python2 and 3 compatible):

try:
  from urllib.parse import urlparse
except ImportError:
  from urlparse import urlparse

**Comment by gabstopper** [comment]
Agreed, sorry I didn't use that  in my example. When loading from the environment in smc-python, I do indeed use that pattern:

    try: 
        from urllib.parse import urlparse 
    except ImportError: 
        from urlparse import urlparse 

I'm going to drop support for python 3.4 and have a run with 3.6. I'll verify this using 3.6 report back shortly.

**Comment by gabstopper** [comment]
Ok, so testing with python 3.6.6 doesn't seem to generate the problem either.
From the IDE directly:
```
>>> try:
...   from urllib.parse import urlparse
... except ImportError:
...   from urlparse import urlparse
... 
>>> parsed = urlparse('http://172.18.1.151:8082')
>>> parsed
ParseResult(scheme='http', netloc='172.18.1.151:8082', path='', params='', query='', fragment='')
>>> parsed.hostname
'172.18.1.151'
>>> parsed.scheme
'http'
>>> parsed.port
8082
>>> 
```

NOTE: Even though you do not see the hostname variable in the ParseResult repr, it is only because the repr for urlparse does not show it. In other words, not seeing it doesn't mean the value would render empty.

Can you put this into a file, run this and send me the output:
```
>>> from smc.api.configloader import load_from_environ
>>> import os
>>> os.environ['SMC_ADDRESS'] = 'https://172.18.1.151:8082'
>>> os.environ['SMC_API_KEY'] = 'xxxxx'
>>> load_from_environ()
{'url': 'https://172.18.1.151:8082', 'api_key': 'xxxxx', 'api_version': None, 'verify': False, 'timeout': None, 'domain': None}
```
The last line is the output from my retrieval of vars from the environment.

Thanks for your help with this! I would also ensure that there is not a shell related issue and try to print the vars before hand, or double check:
```
env | grep SMC
SMC_API_KEY=xxxxx
SMC_ADDRESS=https://172.18.1.151:8082
```

**Comment by gabstopper** [comment]
Hi Darren, 
Checking back on this one, did the above work for you?

**Comment by gabstopper** [comment]
Unable to replicate and no response.
