### ISSUE TITLE
IPPrefixList Collection

### ISSUE THREAD

**Issue by meandus** [gabstopper/smc-python#33]
Internal Error (IPPrefixListCollection(GET /elements?filter=IPL_STORE16_LAN&exact_match=False&filter_context=ip_prefix_list&case_sensitive=True) is not JSON serializable)

                elif object['type'] == 'IPPrefixList':
                    oIPPrefixList = IPPrefixList.objects.filter(object['name'])
                    return oIPPrefixList if oIPPrefixList else False

how can we add exact_match = True ?!

**Comment by gabstopper** [comment]
Hi,
You can add here:
```
from smc.routing.prefix_list import IPPrefixList
oIPPrefixList = IPPrefixList.objects.filter('foo', exact_match=True)
print(oIPPrefixList)
```
IPPrefixListCollection(GET /elements?filter=foo&exact_match=True&filter_context=ip_prefix_list&case_sensitive=True)
