### ISSUE TITLE
Impossible to define max_prefix_length without define min_prefix_length

### ISSUE THREAD

**Issue by meandus** [gabstopper/smc-python#34]

**Comment by gabstopper** [comment]
Hi Meandus,
I'm not entirely sure if I follow, but i'm assuming this has to do with an IP Prefix List?
Testing on SMC 6.4.3, and smc-python 0.6.2 rc.8 (should be same as 0.6.1), it is possible to add a min prefix length without defining the max - which is the same as the SMC UI:

```
IPPrefixList.create(name='foo', entries=[{'subnet': '10.0.0.0/8', 'min_prefix_length': 16, 'action': 'deny'}])
```

![image](https://user-images.githubusercontent.com/14811349/46262547-5a29eb00-c4c8-11e8-9bf3-32262f8d2b28.png)

Am I missing something?
Thanks,

DLP

**Comment by gabstopper** [comment]
Hi Remy,
Which version of SMC do you currently use? Seems that in 6.4.4 this works adding max without min. Even specifying api_version 5.10 on 6.4.3 this works:
```
IPPrefixList.create(name='foo2345', entries=[{'subnet': '10.0.0.0/8', 'max_prefix_length': 16, 'action': 'deny'}])
```
![image](https://user-images.githubusercontent.com/14811349/46985644-17176c80-d0b1-11e8-8734-d4831eb75e22.png)

**Comment by meandus** [comment]
Hi i have smc 6.4.3

RÉMY 

Le 16 octobre 2018 02:32:54 GMT+02:00, David LePage <notifications@github.com> a écrit :
>Hi Remy,
>Which version of SMC do you currently use? Seems that in 6.4.4 this
>works adding max without min. Even specifying api_version 5.10 on 6.4.3
>this works:
>```
>IPPrefixList.create(name='foo2345', entries=[{'subnet': '10.0.0.0/8',
>'max_prefix_length': 16, 'action': 'deny'}])
>```
>![image](https://user-images.githubusercontent.com/14811349/46985644-17176c80-d0b1-11e8-8734-d4831eb75e22.png)
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/gabstopper/smc-python/issues/34#issuecomment-430060199

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by gabstopper** [comment]
Hi Remy,
This also works in 6.4.3. Could you try this and let me know what error you might receive:
```
IPPrefixList.create(name='foo', entries=[{'subnet': '10.0.0.0/8', 'max_prefix_length': 16, 'action': 'deny'}])
```
![image](https://user-images.githubusercontent.com/14811349/47035902-bb94bf80-d140-11e8-8cef-f8fd36ba8447.png)
