### ISSUE TITLE
TunnelInterface

### ISSUE THREAD

**Issue by meandus** [gabstopper/smc-python#37]
Hi David,

Do you have any example to add a tunnel_interface ?

Remy

**Comment by meandus** [comment]
def createTunnelinterface(self, tunnelinterface = {}):
        """ create a tunnel interface
        """

        try:
           engine = Engine(tunnelinterface['target_engine'])
           cluster_tunnel_interface = {
                'comment': tunnelinterface['comment'],
                'tunnel_id': tunnelinterface['tunnel_id'],
                'cluster_virtual': tunnelinterface['cluster_virtual'],
                'network_value': tunnelinterface['network_value'],
                'zone_ref': tunnelinterface['zone_ref']
           }
           pprint(engine)
           if self.engine:
               tunnelinterface=TunnelInterface(cluster_tunnel_interface)
               pprint(tunnelinterface)
               engine.tunnel_interface.add_cluster_virtual_interface(cluster_tunnel_interface)
           status=True
        except Exception,e:
           pprint(e)
           status = False
        finally:
           return status



Result: [Wed Oct 17 16:59:08.805955 2018] [:error] [pid 57534] AttributeError("'dict' object has no attribute 'get_relation'",)

**Comment by meandus** [comment]
if i'm trying to do like Doc:

    def createTunnelinterface(self, tunnelinterface = {}):
        """ create a tunnel interface
        """

        try:
           engine = Engine(tunnelinterface['target_engine'])
           pprint(engine)
           if self.engine:
               engine.tunnel_interface.add_cluster_virtual_interface(tunnel_id=tunnelinterface['tunnel_id'],cluster_virtual=tunnelinterface['cluster_virtual'],network_value=tunnelinterface['network_value'],zone_ref=tunnelinterface['zone_ref'])
           status=True
        except Exception,e:
           pprint(e)
           status = False
        finally:
           return status


TypeError("add_cluster_virtual_interface() got an unexpected keyword argument 'tunnel_id'",)

**Comment by meandus** [comment]
just changed tunnel_id to interface_id and it's ok. Please modify doc :)

**Comment by meandus** [comment]
Please allow to add comment on Interface creation

**Comment by gabstopper** [comment]
Doc corrected in latest dev release

**Comment by meandus** [comment]
Where is the modifications ?

Le 18 octobre 2018 16:01:36 GMT+02:00, David LePage <notifications@github.com> a écrit :
>Doc corrected in latest dev release
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/gabstopper/smc-python/issues/37#issuecomment-431020431

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by gabstopper** [comment]
All new changes are on the develop branch, I will release a new version for 6.4.x versions in the next day/two.

**Comment by meandus** [comment]
But its currently commited on develop right ?

Le 18 octobre 2018 17:18:40 GMT+02:00, David LePage <notifications@github.com> a écrit :
>All new changes are on the develop branch, I will release a new version
>for 6.4.x versions in the next day/two. 
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/gabstopper/smc-python/issues/37#issuecomment-431050118

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by gabstopper** [comment]
You have to click on branches and select develop, then you can link to the documentation:
https://smc-python.readthedocs.io/en/develop/pages/reference.html#module-smc.core.collection

**Comment by meandus** [comment]
Hi David,

After building rbvpn i would like to disable and change from active to standby some tunnels (generated by smc).
Do you know how to do that ?

Read the conf of rbvpn and disable useless tunnels.

Thanks

RÉMY 

Le 18 octobre 2018 18:47:41 GMT+02:00, David LePage <notifications@github.com> a écrit :
>You have to click on branches and select develop, then you can link to
>the documentation:
>https://smc-python.readthedocs.io/en/develop/pages/reference.html#module-smc.core.collection
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/gabstopper/smc-python/issues/37#issuecomment-431081690

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.
