### ISSUE TITLE
Can not add a new host with a comment

### ISSUE THREAD

**Issue by docstephano** [gabstopper/smc-python#4]
Hello,
sorry for my gti-newbee&&python-newbee question.
I want alternatively to list and to create a serie of hosts.

here is my simple code for listing: 0.5.1 on W$
for host in collection.describe_host(name=['vpn_siemens'], exact_match=False):
        print (host.name, " ",host.address, " ",host.href)
        print (host.name, " --> ",host.comment)

The result:
VPN_SIEMENS 171   172.17.134.171   http://172.X.Y.Z:8082/6.1/elements/host/268435587
Traceback (most recent call last):
  File "C:\Python\smc-python-master\smc\STFR_connect.py", line 29, in <module>
    print (host.name, " --> ",host.comment)
AttributeError: 'Host' object has no attribute 'comment'
>>> 

It looks like host.comment does not exist...
Is the comment field not accessible as a string ?

When I want to create a new host with or without comment, it works fine:
print ("Creation with comment")
Host.create(name='STFR_myhost123',address='10.10.10.10')
Host.create(name='STFR_myhost234',address='10.10.10.10',comment='mycomment')
for myhost in collection.describe_host(name=['STFR_myhost'], exact_match=False):
    print (myhost.name, " ",myhost.address, " ",myhost.comment)

it produces such an error:
Creation with comment
Traceback (most recent call last):
  File "C:\Python\smc-python-master\smc\STFR_connect.py", line 39, in <module>
    print (myhost.name, " ",myhost.address, " ",myhost.comment)
AttributeError: 'Host' object has no attribute 'comment'

It may really be a newbie question as I am really new to dev using Python
Ad'ciao
Stephano

BTW, thanks for the great job !-)

**Comment by gabstopper** [comment]
Hi Stephano,
No problem, not a newbie question. You are correct, the ``comment`` attribute is not accessible as a property on the Element directly. However, you can always obtain any attribute's value using ``Element.attr_by_name()``.

Here is an example (also I would recommend updating to the latest version SMC python and using the collections instead of 'describe' methods (they have been deprecated):

```
>>> from smc.elements.network import Host
>>> 
>>> for host in Host.objects.all():
...   host, host.attr_by_name('address'), host.attr_by_name('comment')
... 
(Host(name=SMC), u'172.18.1.150', None)
(Host(name=172.18.1.135), u'172.18.1.135', None)
(Host(name=172.18.2.254), u'172.18.2.254', None)
(Host(name=host), u'1.1.1.1', None)
```

Once you have an element instance, you can access all attributes of that instance by accessing the ``data`` attribute:

```
>>> host = Host('kali')
>>> pprint(host.data)
{u'address': u'22.22.22.22',
 u'comment': u'this is a searchable comment',
 u'ipv6_address': u'2001:db8:85a3::8a2e:370:7334',
 u'key': 978,
 u'link': [{u'href': u'http://172.18.1.150:8082/6.2/elements/host/978',
            u'rel': u'self',
            u'type': u'host'},
           {u'href': u'http://172.18.1.150:8082/6.2/elements/host/978/export',
            u'rel': u'export'},
           {u'href': u'http://172.18.1.150:8082/6.2/elements/host/978/search_category_tags_from_element',
            u'rel': u'search_category_tags_from_element'}],
 u'name': u'kali',
 u'read_only': False,
 u'secondary': [u'7.7.7.7'],
 u'system': False,
 u'third_party_monitoring': {u'netflow': False, u'snmp_trap': False}}
```

The API reference also has exposed attributes documented as well which might help. I am also in the process of exposing more of these very soon to make 'dot' access simpler.

**Comment by gabstopper** [comment]
Some additional search examples:

Hosts with address '1.1.1.1':
```
>>> list(Host.objects.filter('1.1.1.1'))
[Host(name=hax0r), Host(name=host), Host(name=tylercharles), Host(name=hostelement), Host(name=abcdefghijklmnop)]
```
By specific name:
```
>>> list(Host.objects.filter('hax0r'))
[Host(name=hax0r)]
```
By comment with value 'comment':
```
>>> list(Host.objects.filter('comment'))
[Host(name=kiley-test), Host(name=kali), Host(name=kali2), Host(name=abcdefghijklmnop), Host(name=kali3)]
```
In short, when using the 'filter' keyword to narrow the search, this will search the element by type and search against the name, comment and primary key for that element type. For host elements, the primary key is going to be the 'address' field. You can see the same search results from the SMC itself if you were to go to Network Elements->Hosts and start typing '1.1.1.1' for example. You'll notice it narrows the view to elements that match that search parameter. Each element type has a unique primary key and for network elements, it's typically the main value, i.e. for TCP Services it would be port, for Host elements the 'address', for Network, the specified network cidr, etc.
Hope that helps.

**Comment by docstephano** [comment]
Thanks for the Quick and efficient Answer: I'd really need to get deeper in Python !
I'm still wondering why comment is private while name is public then :-)

Concerning primary key for host (and all objets btw), it should rather be the name instead of the IP: it warns you when several objects share the same IP but it simply does not allow you to create two objects (even if fromdifferent types eg a host and a dns) if you try to use the same name...

So, I'll start reading your docs and get more familiar with it since I do have a concrete project that involves domain names on the fly definitions and subrule modification....

Ad'ciao
Stephano

**Comment by gabstopper** [comment]
Hi Stephano,
You are correct, I don't think I explained it correctly. The name field IS the primary key for an element; what I meant to explain was that when doing searches other fields are also part of the search criteria (better termed 'field'). For example, when doing a host search, the 'filter' value will match against name, comment, address and secondary (additional IPs assigned), and the IPv6 address field. That way if you don't know the name you can also search by an elements field as well.
Another thing to note about naming; the SMC is case sensitive for naming. So you can have a host named 'kali' and another 'Kali' and they are unique elements:

```
>>> list(Host.objects.filter('kali'))
[Host(name=kali), Host(name=kali2), Host(name=Kali), Host(name=kali3)]
```

This is where the 'exact_match' parameter comes in. If you want to do a case sensitive match, use this switch:
```
>>> list(Host.objects.filter('Kali',exact_match=True))
[Host(name=Kali)]
```

In terms of comment field being private, that is only temporary. Some work was recently done to focus on caching structure to reduce number of required queries to SMC and the next release (due in the next day/two) will expose the network element attributes for simple access. They are accessible today, just not in the most friendly manner (i.e. they can be modified by accessing via ``data`` attribute).

**Comment by gabstopper** [comment]
Hi Stephano,
I pushed an update that exposes all attributes of elements and updated the documentation accordingly. For example:

```
>>> for host in Host.objects.filter('1.1.1.1'):
...   print(host.name, host.address, host.comment)
... 
(u'hax0r', u'1.1.1.1', u'foobar')
(u'host', u'1.1.1.1', None)
(u'tylercharles', u'1.1.1.1', None)
(u'hostelement', u'1.1.1.1', None)
(u'abcdefghijklmnop', u'1.1.1.1', u'comment')
```

Each element type will have documented attributes available. Documentation for each class is found in the API Reference:

For the example above:
http://smc-python.readthedocs.io/en/latest/pages/reference.html#host

Let me know if you need any help with the domain / policy concepts.

**Comment by docstephano** [comment]
Thanks a lot.
Great noticeable reactivity.
I ´ll give it a try or two this week if emergency levels are slowing down :-)


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by gabstopper** [comment]
I just updated 0.5.2rc1 today. Since you are going to work with sub policies, here's a quick start for you. 

To get a policy context (assuming it's created), get by type:

```python
>>> from smc.policy.layer3 import FirewallSubPolicy
>>> policy = FirewallSubPolicy('aws vpn')
>>> for rule in policy.ipv4_access_rules.all():
...   print(rule, rule.name, rule.sources, rule.destinations)
... 
IPv4Rule(name=Rule @2098927.3) Rule @2098927.3 <smc.policy.rule_elements.Source object at 0x105d623c8> <smc.policy.rule_elements.Destination object at 0x105cbbac8> <smc.policy.rule_elements.Service object at 0x105cbb438> <smc.policy.rule_elements.Action object at 0x105cbb898>
```
It is advisable that when you create your rules, you give them a name otherwise the SMC will tag them with 'Rule @xxxxxxx.x' syntax and they would be harder to find in the future.

You'll notice source/destination and service fields will return objects that encapsulate their settings. These fields use the mixin 'RuleElement' which also allow easy modification:
http://smc-python.readthedocs.io/en/latest/pages/reference.html#module-smc.policy.rule_elements.

If you need to add DomainName elements, these are referenced by name, otherwise you might consider IPList's as well. Depending on your need.

**Comment by docstephano** [comment]
Hello David
Thanks for the detailed information. I'm currently stucked in a training room playing with Stormshield fw: I won't be able to test it before next week !-)

Btw, yes I'd need some domain names included into this sub policy. If that's working one day as expected, I'd probably write a short article on it.

Thanks again for all the great jon AND support :-)

Get Outlook for iOS<https://aka.ms/o0ukef>
_____________________________

**Comment by gabstopper** [comment]
Not a problem. And Domain Names work today without a problem. Here is an example of adding to a rule (after getting or creating the DomainName elements:

```python
domains = []
    for domain in ['lepages.net', 'microsoft.com', 'amazon.com', 'foo.local']:
        domains.append(DomainName.get_or_create(name=domain, comment='added by smc-python'))
        
policy = FirewallSubPolicy('MySubPolicy')
policy.fw_ipv4_access_rules.create(
    name='mydomainrule',
    sources='any',
    destinations=domains,
    services=[TCPService('HTTPS')],
    action='discard')
    
rule = policy.search_rule('mydomainrule')[0] # Get the rule directly
print(rule.name,
      rule.sources.is_any,
      rule.destinations.all(),
      rule.services.all(),
      rule.action.action)
```

Here's a GUI screenshot:

![image](https://cloud.githubusercontent.com/assets/14811349/26328184/99625bce-3f07-11e7-9a81-a49aba1d43a0.png)

**Comment by gabstopper** [comment]
Hi there, just wondering if it's ok to close this particular issue? Please let me know how things are going also! Thanks, David

**Comment by docstephano** [comment]
Hello David
I had no time to finish my coding yet :-(
I hopeto do it end of this month.
I'll keep you updated...
Cheers

Obtenez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________

**Comment by docstephano** [comment]
Hello David,
I spent some time on customer's site and figured out my VPN_ON_DEMAND feature without the need to modify the subpolicy using the API: the customer wants to do it manually.
Works fine with me.
You can close this topic and continue to upgrade this nice product :-)
Cheers and thanks for your help again.
