### ISSUE TITLE
BGPPeering(name=SOMETHING)

### ISSUE THREAD

**Issue by meandus** [gabstopper/smc-python#43]
Hi David,

Is it possible to have BGPPeering(name="SOMETHING") instead of BGPPeering(name=SOMETHING)

NameError: name 'SOMETHING' is not defined

When i create a BGPPeering, I receive this object and want to serialize this object to store into DB for Rollback and Configuration

That's the same for all kind of object

May be you have a correct function to serialize objects ?

Thanks in advance,

Rémy

**Comment by gabstopper** [comment]
Hi Remy,
All Element, SubElement and UserElement types support serialization through pickle. Here is an example:

```
>>> from smc.routing.bgp import BGPPeering
>>> bgp = BGPPeering('bgppeering')
>>> print(bgp)
BGPPeering(name=bgppeering)
>>> import pickle
>>> pickled = pickle.dumps(bgp, protocol=2)
>>> pickled
'\x80\x02csmc.routing.bgp\nBGPPeering\nq\x00)\x81q\x01}q\x02(U\x04dataq\x03}q\x04(X\x07\x00\x00\x00commentq\x05X\x03\x00\x00\x00fooq\x06X\x11\x00\x00\x00default_originateq\x07\x89X\x14\x00\x00\x00soft_reconfigurationq\x08\x88X\n\x00\x00\x00ttl_optionq\tX\x08\x00\x00\x00disabledq\nX\x04\x00\x00\x00nameq\x0bX\n\x00\x00\x00bgppeeringq\x0cX\x13\x00\x00\x00override_capabilityq\r\x89X\x0f\x00\x00\x00local_as_optionq\x0eX\x07\x00\x00\x00not_setq\x0fX\x12\x00\x00\x00connection_profileq\x10X?\x00\x00\x00https://172.18.1.151:8082/6.5/elements/bgp_connection_profile/1q\x11X\x0e\x00\x00\x00send_communityq\x12X\x02\x00\x00\x00noq\x13X\n\x00\x00\x00orf_optionq\x14X\x08\x00\x00\x00disabledq\x15X\x16\x00\x00\x00route_reflector_clientq\x16\x89X\t\x00\x00\x00read_onlyq\x17\x89X\x04\x00\x00\x00linkq\x18]q\x19(}q\x1a(X\x04\x00\x00\x00hrefq\x1bX4\x00\x00\x00https://172.18.1.151:8082/6.5/elements/bgp_peering/1q\x1cX\x04\x00\x00\x00typeq\x1dX\x0b\x00\x00\x00bgp_peeringq\x1eX\x03\x00\x00\x00relq\x1fX\x04\x00\x00\x00selfq u}q!(X\x04\x00\x00\x00hrefq"X;\x00\x00\x00https://172.18.1.151:8082/6.5/elements/bgp_peering/1/exportq#X\x03\x00\x00\x00relq$X\x06\x00\x00\x00exportq%u}q&(X\x04\x00\x00\x00hrefq\'X<\x00\x00\x00https://172.18.1.151:8082/6.5/elements/bgp_peering/1/historyq(X\x03\x00\x00\x00relq)X\x07\x00\x00\x00historyq*u}q+(X\x04\x00\x00\x00hrefq,XV\x00\x00\x00https://172.18.1.151:8082/6.5/elements/bgp_peering/1/search_category_tags_from_elementq-X\x03\x00\x00\x00relq.X!\x00\x00\x00search_category_tags_from_elementq/u}q0(X\x04\x00\x00\x00hrefq1X>\x00\x00\x00https://172.18.1.151:8082/6.5/elements/bgp_peering/1/duplicateq2X\x03\x00\x00\x00relq3X\t\x00\x00\x00duplicateq4ueX\x03\x00\x00\x00keyq5K\x01X\r\x00\x00\x00next_hop_selfq6\x88X\x11\x00\x00\x00max_prefix_optionq7X\x0b\x00\x00\x00not_enabledq8X\x06\x00\x00\x00systemq9\x89X\x11\x00\x00\x00remove_private_asq:\x89X\x19\x00\x00\x00dont_capability_negotiateq;\x89X\x0f\x00\x00\x00connected_checkq<X\x08\x00\x00\x00disabledq=uU\x05_metaq>csmc.base.model\nMeta\nq?X\n\x00\x00\x00bgppeeringq@X4\x00\x00\x00https://172.18.1.151:8082/6.5/elements/bgp_peering/1qAX\x0b\x00\x00\x00bgp_peeringqB\x87qC\x81qDU\x05_nameqEU\nbgppeeringqFub.'
>>> 
... 
>>> loaded = pickle.loads(pickled)
>>> print(loaded)
BGPPeering(name=bgppeering)
```

**Comment by meandus** [comment]
H David,

I've just found solution with cPickle and base64 and it works.

I will update the ticket with the best solution.

Rémy 

Le 21 novembre 2018 21:30:13 GMT+01:00, David LePage <notifications@github.com> a écrit :
>Hi Remy,
>All Element, SubElement and UserElement types support serialization
>through pickle. Here is an example:
>
>```
>>>> from smc.routing.bgp import BGPPeering
>>>> bgp = BGPPeering('bgppeering')
>>>> print(bgp)
>BGPPeering(name=bgppeering)
>>>> import pickle
>>>> pickled = pickle.dumps(bgp, protocol=2)
>>>> pickled
>'\x80\x02csmc.routing.bgp\nBGPPeering\nq\x00)\x81q\x01}q\x02(U\x04dataq\x03}q\x04(X\x07\x00\x00\x00commentq\x05X\x03\x00\x00\x00fooq\x06X\x11\x00\x00\x00default_originateq\x07\x89X\x14\x00\x00\x00soft_reconfigurationq\x08\x88X\n\x00\x00\x00ttl_optionq\tX\x08\x00\x00\x00disabledq\nX\x04\x00\x00\x00nameq\x0bX\n\x00\x00\x00bgppeeringq\x0cX\x13\x00\x00\x00override_capabilityq\r\x89X\x0f\x00\x00\x00local_as_optionq\x0eX\x07\x00\x00\x00not_setq\x0fX\x12\x00\x00\x00connection_profileq\x10X?\x00\x00\x00https://172.18.1.151:8082/6.5/elements/bgp_connection_profile/1q\x11X\x0e\x00\x00\x00send_communityq\x12X\x02\x00\x00\x00noq\x13X\n\x00\x00\x00orf_optionq\x14X\x08\x00\x00\x00disabledq\x15X\x16\x00\x00\x00route_reflector_clientq\x16\x89X\t\x00\x00\x00read_onlyq\x17\x89X\x04\x00\x00\x00linkq\x18]q\x19(}q\x1a(X\x04\x00\x00\x00hrefq\x1bX4\x00\x00\x00https://172.18.1.151:8082/6.5/elements/bgp_peering/1q\x1cX\x04\x00\x00\x00typeq\x1dX\x0b\x00\x00\x00bgp_peeringq\x1eX\x03\x00\x00\x00relq\x1fX\x04\x00\x00\x00selfq
>u}q!(X\x04\x00\x00\x00hrefq"X;\x00\x00\x00https://172.18.1.151:8082/6.5/elements/bgp_peering/1/exportq#X\x03\x00\x00\x00relq$X\x06\x00\x00\x00exportq%u}q&(X\x04\x00\x00\x00hrefq\'X<\x00\x00\x00https://172.18.1.151:8082/6.5/elements/bgp_peering/1/historyq(X\x03\x00\x00\x00relq)X\x07\x00\x00\x00historyq*u}q+(X\x04\x00\x00\x00hrefq,XV\x00\x00\x00https://172.18.1.151:8082/6.5/elements/bgp_peering/1/search_category_tags_from_elementq-X\x03\x00\x00\x00relq.X!\x00\x00\x00search_category_tags_from_elementq/u}q0(X\x04\x00\x00\x00hrefq1X>\x00\x00\x00https://172.18.1.151:8082/6.5/elements/bgp_peering/1/duplicateq2X\x03\x00\x00\x00relq3X\t\x00\x00\x00duplicateq4ueX\x03\x00\x00\x00keyq5K\x01X\r\x00\x00\x00next_hop_selfq6\x88X\x11\x00\x00\x00max_prefix_optionq7X\x0b\x00\x00\x00not_enabledq8X\x06\x00\x00\x00systemq9\x89X\x11\x00\x00\x00remove_private_asq:\x89X\x19\x00\x00\x00dont_capability_negotiateq;\x89X\x0f\x00\x00\x00connected_checkq<X\x08\x00\x00\x00disabledq=uU\x05_metaq>csmc.base.model\nMeta\nq?X\n\x00\x00\x00bgppeeringq@X4\x00\x00\x00https://172.18.1.151:8082/6.5/elements/bgp_peering/1qAX\x0b\x00\x00\x00bgp_peeringqB\x87qC\x81qDU\x05_nameqEU\nbgppeeringqFub.'
>>>> 
>... 
>>>> loaded = pickle.loads(pickled)
>>>> print(loaded)
>BGPPeering(name=bgppeering)
>```
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/gabstopper/smc-python/issues/43#issuecomment-440799640

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by meandus** [comment]
### I made a tracing librairie to record all objects and actions done on the firewall config
goal is to record into DB and be able to rollback later if necessary or duplicate

**Here my table in postgres:**
```
CREATE TABLE firewall_config (
    engine_name CHARACTER VARYING(30) NOT NULL,
    configuration TEXT NOT NULL
);
```


```
import smc...
import cPickle

config = {'RBVPN': [u'VPN-FWCUST-FWEXT2', u'VPN-FWCUST-FWEXT1'], 'TunnelInterface': [{'comment': u'to FWCUST', 'zone_ref': None, 'target_engine': 'FWEXT2', 'cluster_virtual': '1.1.4.1', 'tunnel_id': 1021, 'network_value': u'1.1.4.0/30'}, {'comment': 'to FWEXT2', 'zone_ref': None, 'target_engine': u'FWCUST', 'cluster_virtual': '1.1.4.2', 'tunnel_id': 1021, 'network_value': u'1.1.4.0/30'}, {'comment': u'to FWCUST', 'zone_ref': None, 'target_engine': 'FWEXT1', 'cluster_virtual': '10.252.4.1', 'tunnel_id': 2021, 'network_value': u'10.252.4.0/30'}, {'comment': 'to FWEXT1', 'zone_ref': None, 'target_engine': u'FWCUST', 'cluster_virtual': '10.252.4.2', 'tunnel_id': 2021, 'network_value': u'10.252.4.0/30'}], 'AntispoofToInterface': [{'engine': u'FWCUST', 'elements': [{'type': 'Group', 'name': 'GN_DCs-DATACENTER'}, {'type': 'Group', 'name': 'GN_NC_STA'}], 'interface_id': 1021}, {'engine': u'FWCUST', 'elements': [{'type': 'Group', 'name': 'GN_DCs-DATACENTER'}, {'type': 'Group', 'name': 'GN_NC_STA'}], 'interface_id': 2021}], 'BGPRouteToInterface': [{'engine': 'FWEXT2', 'bgp_peering': BGPPeering(name="FWEXT1_to_FWCUST"), 'ext_bgp_peer': ExternalBGPPeer(name="PEER_FWCUST_HQ_to_FWEXT1"), 'interface_id': 1021}, {'engine': u'FWCUST', 'bgp_peering': BGPPeering(name="FWCUST_to_FWEXT1"), 'ext_bgp_peer': ExternalBGPPeer(name="PEER_FWEXT1_to_FWCUST_HQ"), 'interface_id': 1021}, {'engine': 'FWEXT1', 'bgp_peering': BGPPeering(name="FWEXT2_to_FWCUST"), 'ext_bgp_peer': ExternalBGPPeer(name="PEER_FWCUST_HQ_to_FWEXT2"), 'interface_id': 2021}, {'engine': u'FWCUST', 'bgp_peering': BGPPeering(name="FWCUST_to_FWEXT2"), 'ext_bgp_peer': ExternalBGPPeer(name="PEER_FWEXT2_to_FWCUST_HQ"), 'interface_id': 2021}], 'objects': [], 'BGPEnabledEngine': [u'FWCUST'], 'RouteMapRules': [{'routemap': RouteMap(name="FWCUST_ALL"), 'rule': u'permitHQ'}, {'routemap': RouteMap(name="ALL_SELECTED_BGP"), 'rule': u'permitFWCUST_HQ'}]}

> Encode to str

engine_name = FWCUST

sEncodedConfig= cPickle.dumps(config).encode("zip").encode("base64").strip()
sQuery="INSERT INTO firewall_config (fw_id,configuration) VALUES ((SELECT id FROM win_firewall WHERE name = '%s'),'%s') RETURNING fw_id" % (engine_name,sEncodedConfig)
pprint(sQuery)

> Decode to dict

dDecodedConfig= cPickle.loads(configtext.decode("base64").decode("zip"))
pprint(dDecodedConfig)
oRouteMap = dDecodedConfig['RouteMapRules'][0]['routemap']
pprint(oRouteMap .href)
```

**Comment by gabstopper** [comment]
Hi Remy,
Thanks for posting this example! This is an interesting idea also. I have been experimenting with a "transaction manager" where you could decorate functions which would track changes and optionally rollback based on "savepoints" within the function. It's modeled after Django transactions. I haven't yet posted it as i'm not entirely sure it will be useful but I can push in next dev update if it's something of interest. The only limitation currently is that tracking is only possible on `create` operations.

It would look like this.

The first example is wrapping an existing function. Any failures in the function result in a rollback of all previously successful operations:

```
from smc.base import transaction
     
@transaction.atomic()
def mytasks():
    for name in range(1, 10):
        Host.create(name='host%s' % name, address='1.1.1.1')
     
    Network.create(name='mynet2', ipv4_network='1.1.1.0/24')
     
    print("Now fail")
    Host.create(name='host2', address='1.1.1.1')
```

The second example is using the transaction manager as a context manager. 
This might be interesting if you wanted to create "savepoints" in the process where you wouldn't roll back all changes, but only some up to a certain point:  

```
with transaction.atomic():
    for name in range(1, 10):
        Host.create(name='host%s' % name, address='1.1.1.1')
     
    Network.create(name='mynet2', ipv4_network='1.1.1.0/24')
     
    print("Now fail")
    Host.create(name='host2', address='1.1.1.1')
```

This is the example of using a nested context manager which creates a new rollback savepoint.
The savepoint is created when a context manager is nested within another (no limit on the nesting).
This allows you to provide a logical rollback point where some operations are not rolled back but others would be:
```
with transaction.atomic():
    for name in range(1, 10):
        Host.create(name='host%s' % name, address='1.1.1.1')
        
    with transaction.atomic(): # <-- Nested context manager, saves all previous actions
        Network.create(name='mynet3', ipv4_network='1.1.1.0/24')
         
    print("Now fail")
    Host.create(name='host2', address='1.1.1.1')
```

**Comment by meandus** [comment]
Yes very interesting and optionnaly to savr in db because sometimes rollback need to be later.



Le 22 novembre 2018 03:21:08 GMT+01:00, David LePage <notifications@github.com> a écrit :
>Hi Remy,
>Thanks for posting this example! This is an interesting idea also. I
>have been experimenting with a "transaction manager" where you could
>decorate functions which would track changes and optionally rollback
>based on "savepoints" within the function. It's modeled after Django
>transactions. I haven't yet posted it as i'm not entirely sure it will
>be useful but I can push in next dev update if it's something of
>interest. The only limitation currently is that tracking is only
>possible on `create` operations.
>
>It would look like this.
>
>The first example is wrapping an existing function. Any failures in the
>function result in a rollback of all previously successful operations:
>
>```
>from smc.base import transaction
>     
>@transaction.atomic()
>def mytasks():
>    for name in range(1, 10):
>        Host.create(name='host%s' % name, address='1.1.1.1')
>     
>    Network.create(name='mynet2', ipv4_network='1.1.1.0/24')
>     
>    print("Now fail")
>    Host.create(name='host2', address='1.1.1.1')
>```
>
>The second example is using the transaction manager as a context
>manager. 
>This might be interesting if you wanted to create "savepoints" in the
>process where you wouldn't roll back all changes, but only some up to a
>certain point:  
>
>```
>with transaction.atomic():
>    for name in range(1, 10):
>        Host.create(name='host%s' % name, address='1.1.1.1')
>     
>    Network.create(name='mynet2', ipv4_network='1.1.1.0/24')
>     
>    print("Now fail")
>    Host.create(name='host2', address='1.1.1.1')
>```
>
>This is the example of using a nested context manager which creates a
>new rollback savepoint.
>The savepoint is created when a context manager is nested within
>another (no limit on the nesting).
>This allows you to provide a logical rollback point where some
>operations are not rolled back but others would be:
>```
>with transaction.atomic():
>    for name in range(1, 10):
>        Host.create(name='host%s' % name, address='1.1.1.1')
>        
>with transaction.atomic(): # <-- Nested context manager, saves all
>previous actions
>        Network.create(name='mynet3', ipv4_network='1.1.1.0/24')
>         
>    print("Now fail")
>    Host.create(name='host2', address='1.1.1.1')
>```
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/gabstopper/smc-python/issues/43#issuecomment-440892657

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by meandus** [comment]
I have to move 850 firewalls to new config and goal is to record all transactions and got objects AND actions to rollback if necessary.



Le 22 novembre 2018 03:21:08 GMT+01:00, David LePage <notifications@github.com> a écrit :
>Hi Remy,
>Thanks for posting this example! This is an interesting idea also. I
>have been experimenting with a "transaction manager" where you could
>decorate functions which would track changes and optionally rollback
>based on "savepoints" within the function. It's modeled after Django
>transactions. I haven't yet posted it as i'm not entirely sure it will
>be useful but I can push in next dev update if it's something of
>interest. The only limitation currently is that tracking is only
>possible on `create` operations.
>
>It would look like this.
>
>The first example is wrapping an existing function. Any failures in the
>function result in a rollback of all previously successful operations:
>
>```
>from smc.base import transaction
>     
>@transaction.atomic()
>def mytasks():
>    for name in range(1, 10):
>        Host.create(name='host%s' % name, address='1.1.1.1')
>     
>    Network.create(name='mynet2', ipv4_network='1.1.1.0/24')
>     
>    print("Now fail")
>    Host.create(name='host2', address='1.1.1.1')
>```
>
>The second example is using the transaction manager as a context
>manager. 
>This might be interesting if you wanted to create "savepoints" in the
>process where you wouldn't roll back all changes, but only some up to a
>certain point:  
>
>```
>with transaction.atomic():
>    for name in range(1, 10):
>        Host.create(name='host%s' % name, address='1.1.1.1')
>     
>    Network.create(name='mynet2', ipv4_network='1.1.1.0/24')
>     
>    print("Now fail")
>    Host.create(name='host2', address='1.1.1.1')
>```
>
>This is the example of using a nested context manager which creates a
>new rollback savepoint.
>The savepoint is created when a context manager is nested within
>another (no limit on the nesting).
>This allows you to provide a logical rollback point where some
>operations are not rolled back but others would be:
>```
>with transaction.atomic():
>    for name in range(1, 10):
>        Host.create(name='host%s' % name, address='1.1.1.1')
>        
>with transaction.atomic(): # <-- Nested context manager, saves all
>previous actions
>        Network.create(name='mynet3', ipv4_network='1.1.1.0/24')
>         
>    print("Now fail")
>    Host.create(name='host2', address='1.1.1.1')
>```
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/gabstopper/smc-python/issues/43#issuecomment-440892657

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by gabstopper** [comment]
I will mark this as solved but I am interested in how to migration is going. Feel free to ping me out of band.

**Comment by meandus** [comment]
So far so good but need to disable some tunnels created by smc ... during vpn config for route or policy...if we add a new endpoint ...we need also to disable tunnels. Do you have any updates for that feature on api ?

Le 18 janvier 2019 10:52:34 GMT+01:00, David LePage <notifications@github.com> a écrit :
>I will mark this as solved but I am interested in how to migration is
>going. Feel free to ping me out of band.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/gabstopper/smc-python/issues/43#issuecomment-455489335

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.
