### ISSUE TITLE
routemap and smc 6.4.7

### ISSUE THREAD

**Issue by meandus** [gabstopper/smc-python#46]
Hi David,

Im not able anymore to create a routemap on 6.4.7 without changes. Could you test and let me know which version is correct to avoid issue ?

Thanks
Rémy POUCHAIN

**Comment by gabstopper** [comment]
Hi Remy,
Do you have a sample that doesn't work and the error you are receiving? That would help me chase down what changed on SMC API to address.

Thanks!

**Comment by gabstopper** [comment]
Hi Remy,
Is this still an issue for you? I haven't heard back and wasn't able to reproduce this.

**Comment by gabstopper** [comment]
Closing, unreproducible

**Comment by meandus** [comment]
Bug is on 6.4.7 , known on stonesoft api side, 6.4.8 is ok. 

Le 17 avril 2019 18:58:43 GMT+02:00, David LePage <notifications@github.com> a écrit :
>Closing, unreproducible
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/gabstopper/smc-python/issues/46#issuecomment-484175174

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.
