### ISSUE TITLE
Add Security Group to Access Rules

### ISSUE THREAD

**Issue by doctori** [gabstopper/smc-python#5]
Hi,  

I'm trying to add a Security group to an Access Rules,
But I cannot find any Object that would represent a Security Group, 
Am I Missing something ?  
or is it simply not implemented yet ?  

Thanks for your awnsers

**Comment by gabstopper** [comment]
Hi,
The SecurityGroup element type is a special group container that probably should be hidden. It's purpose only pertains to integration with NSX. I will fix that documentation. It's essentially no different than using a normal Group element however (with some minor differences on the engine backend). To create the group:
```
network = Network.get_or_create(name='mynetwork', ipv4_network='1.1.1.0/24')
host = Host.get_or_create(name='myhost', address='2.2.2.2')
Group.create(name='group1', members=[network, host], comment='my security group')
```

Then you can use the group element as your rule source/destination.

DLP

**Comment by gabstopper** [comment]
Hi Doctori,
Please confirm if the above worked for you. Note that you can find other group types for policy access under the Elements docs: http://smc-python.readthedocs.io/en/latest/pages/reference.html#module-smc.elements.group

There are multiple group types as well, i.e. network element group, ip service group, tcp server group, etc.

**Comment by gabstopper** [comment]
Just checking back on this to see if you were able to resolve with my instructions?

**Comment by gabstopper** [comment]
Hi, just checking back that you were able to resolve this with my instructions. As this has been open for awhile i'm going to go ahead and close. Please reopen if the issue still exists.
