### ISSUE TITLE
Rule action with SMC 6.6

### ISSUE THREAD

**Issue by Alrexxar** [gabstopper/smc-python#54]
Hi David
I just tried to write a script using the new 6.6 version of the SMC.
In the API reference of readthedocs i already saw that a rule action now needs to be passed on as a list, but im not quite sure how to do it.
When assigning the rule action as a string as I was used to do in earlier versions an Error is raised:
`smc.api.exceptions.CreateRuleFailed: Invalid JSON format: Cannot deserialize instance of `java.util.ArrayList` out of VALUE_STRING token at [line: 1, column: 475] (from: FWRuleActionDTO["action"]).`

Still the same happens commiting the rule action as a list.

Maybe you understand my problem and can help me with this issue.

Best Regards
Niels

**Comment by gabstopper** [comment]
Hi Niels,
You must update to the dev branch to get the updates for SMC 6.6.

**Comment by Alrexxar** [comment]
Thanks a lot!

**Comment by Alrexxar** [comment]
I have to reopen the issue...:
I upgraded to the dev branch but i still get the same error message even when trying to create a rule without a defined action.
Though the code reference changed a bit from
`Cannot deserialize instance of java.util.ArrayList out of VALUE_STRING token at [line: 1, column: 475] (from: FWRuleActionDTO["action"]).`
to
`Invalid JSON format: Cannot deserialize instance of `java.util.ArrayList` out of VALUE_STRING token at [line: 1, column: 193] (from: FWRuleActionDTO["action"])`

**Comment by gabstopper** [comment]
Hi Alrexxar,
Due to changes in 6.6 you should pass some value for the action field when creating the rule. I will open a FMR against the SMC API as it should allow a default action automatically (like SMC <= 6.5) when one is not provided. Going forward, the smc-python API will eventually start enforcing a specific version based on which SMC version it is connecting to in which case we can also move that logic into smc-python.

**Comment by Alrexxar** [comment]
Hi David,
Could you provide a working example how to pass the action as a list?
I get errors all the time and i dont quite know how to continue.
Best Regards
Niels

**Comment by Alrexxar** [comment]
Nevermind,
i finally got it using python3.6 instead of 2.7

**Comment by juju89** [comment]
Hi Alrexxar,
I saw you closed the case by saying that it works for you with python3.6. I had the exact same problem and I switched to python 3.6 but got it still :/ 
Could you Tell how you manage to make it Work please ?

**Comment by gabstopper** [comment]
Hi there,
In 6.6 the rule structure changed and you can simply pass the value as a
list instead of a string.

i.e.
policy.fw_ipv4_access_rules.create(name='foo', action=['discard'],
services='any')

**Comment by juju89** [comment]
Hi David,
It doesn't Work for me to give the list Like you do, althought I got a different error now :
smc.api.exceptions.CreateRuleFailed: Action specified is not valid for this rule type; action: ['discard']

**Comment by gabstopper** [comment]
My apologies, I forgot to mention that you will need the develop branch of
smc-python. We are staging develop to release soon to fully support 6.6 but
most features will work already (there are a few edge cases around virtual
engines that will be problematic).
Please update to the develop branch and this will work.

**Comment by juju89** [comment]
That was it ! 
Thank you so much for you help David, it's now working :)

**Comment by gabstopper** [comment]
Not a problem!
