### ISSUE TITLE
smc_monitoring + filter + Situation

### ISSUE THREAD

**Issue by Maheine** [gabstopper/smc-python#56]
Hi David,
I'm using smc_monitoring and want to filter for a Situation. Situations are represented by integers. Therefor the following code have to fail:

```
query = ActiveAlertQuery('Shared Domain', timezone='Berlin/Europe')
query.add_in_filter(
    FieldValue(LogField.SITUATION), [StringValue('519')])
for record in query.fetch_batch():
    print(record)

```

```
Traceback (most recent call last):
  File "/root/dev/login_failed.py", line 28, in <module>
    for record in query.fetch_batch():
  File "/usr/lib/python2.7/site-packages/smc_python_monitoring-1.2.0-py2.7.egg/smc_monitoring/models/query.py", line 310, in fetch_batch
    for result in self.fetch_raw(**kw):
  File "/usr/lib/python2.7/site-packages/smc_python_monitoring-1.2.0-py2.7.egg/smc_monitoring/models/query.py", line 292, in fetch_raw
    protocol.abort()
  File "/usr/lib/python2.7/site-packages/smc_python_monitoring-1.2.0-py2.7.egg/smc_monitoring/wsocket.py", line 129, in __exit__
    raise FetchAborted(value)
smc_monitoring.wsocket.FetchAborted: TransactionFactory throws Exception
Details:
Failed to start query
Cannot add Literal String to Operation in.
Type mismatch: Number (int) and String.
```

Another way to filter for the alerts is producing an endless running script with no return:
```
query = ActiveAlertQuery('Shared Domain', timezone='Berlin/Europe')
query.add_in_filter(
    FieldValue(LogField.INFOMSG), [StringValue('login')])
for record in query.fetch_batch():
    print(record)
```

This filter is working fine, but returns too much:
```
query = ActiveAlertQuery('Shared Domain', timezone='Berlin/Europe')
query.add_in_filter(
    FieldValue(LogField.ALERTSEVERITY), [ConstantValue(Alerts.LOW)])
for record in query.fetch_batch():
    print(record)
```

Is there any possibility to filter for a special Situation? Is there a NumberValue that can be used for the add_in_filter?

And why is the INFOMSG/StringValue filter running endless? Did I miss something?

SMC: 6.5.4 / Python 2.7 / smc_monitoring 1.2.0

Best Regards
Marten

**Comment by gabstopper** [comment]
Hi Marten,
It appears the NumberValue field is currently not implemented against Situations, however you can retrieve them still - I would recommend using a simple "TranslatedFilter". When you go into Log Viewer and right click an existing filter, this will be the value shown there. It's a raw way to provide the filter but based on a quick query does work with Situations.
For example:
```
t_filter = TranslatedFilter()
t_filter.update_filter('$Situation==516')
    
query = ActiveAlertQuery('Shared Domain', timezone='Berlin/Europe')
query.update_filter(t_filter)

for record in query.fetch_batch():
    print(record)
```

In terms of other questions, the StringValue query should return the same as what you would see in the SMC UI - do you get results when running a similar query?
By default a fetch_batch query will only grab the first batch of data - if no data is returned then it will wait for the data and then exit.

It is possible to provide max_recv to fetch_batch, which would provide a limit to the number of batches that are returned by the query API. However if no results are found, you will get the blocking behavior until it's aborted (similar to the Log Viewer).

**Comment by gabstopper** [comment]
Please confirm that this works for you. I will push a feature request to normalize the logic using a Number filter as well.

**Comment by gabstopper** [comment]
Closing due to workaround - albeit, will implement logic more inline with other filter types.

**Comment by Maheine** [comment]
Hi David,
sorry for the late respond, I have been in Helsinki the last days.
The workaround for the Situation works perfect, thanks for that.

Is there any way to get a timeout for query.fetch_batch like it is in query.execute, so the blocking behavior do not occur, or do I have to write an own function?
