### ISSUE TITLE
AS Path Prepend in RouteMap

### ISSUE THREAD

**Issue by EtienneMILON** [gabstopper/smc-python#59]
Hi David,

I try to add an AS Path Prepend in a Route Map rule, I cannot find it with smc-python:
![image](https://user-images.githubusercontent.com/41421040/60435292-77cbe280-9c09-11e9-9ac3-951fb0fe3b29.png)
![image](https://user-images.githubusercontent.com/41421040/60435320-8d410c80-9c09-11e9-814f-38d85014c699.png)

Is it possible?

Best Regards,
Etienne

**Comment by gabstopper** [comment]
Hi, 
I will add an interface for this but it is still currently possible to do.
Here is an example:

```
prefix_list = IPPrefixList('testiplist')
routemap = RouteMap('testroutemap')
# Create a route map rule
rule = routemap.route_map_rules.create(name='rule1', access_list=prefix_list)
# Now update
rule.update(route_entry_settings={'as_path_type': 'prepend', 'as_number': [{'expression': '123456789'}]})
```
as_path_type specifies the action (dont_modify/prepend/exclude). If prepend or exclude are specified you will need the `as_number` attribute as well.

Let me know if that works for you and I'll add a cleaner way to do this from the route map rule.

David

**Comment by EtienneMILON** [comment]
Hi David,

Thanks for your answer.
It works for me.

Etienne
