### ISSUE TITLE
JSON problem

### ISSUE THREAD

**Issue by jenhek** [gabstopper/smc-python#6]
On CentOS7, Ubuntu 16:

  File "/usr/local/lib/python2.7/dist-packages/smc/api/session.py", line 298, in available_api_versions
    j = json.loads(r.text)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")

Any idea what we do wrong?

Jens

**Comment by gabstopper** [comment]
Hi Jens,
This appears to be related to the initial API version discovery and the response being returned.
Based on the messages the response data is not what was expected and cannot be serialized.
Could you attempt to enable debug logging on the smc-python side by adding the following to your script:

```
import logging
logging.getLogger()
logging.basicConfig(
        level=logging.DEBUG, format='%(asctime)s %(levelname)s %(name)s.%(funcName)s: %(message)s')
```

Also, how is the SMC information being provided to the login session? The simplest and quickest way would be to insert this into your script. You can then move this to either environment variables or config file as well but this can help make it easier initially:
```
from smc import session

session.login(url='http://1.1.1.1:8082', api_key='xxxxxxxxxxxxxxxxx')
....do stuff....
session.logout()
```

One last question, which version of SMC are you using?

**Comment by jenhek** [comment]
Hi,

at the momnent my script is very short, just this:

---------------------------------------

session.login(url='http://134.130.X.Y:8082', api_key='mykey', api_version='6.2.1')

session.logout()

---------------------------------------

The error thrown and debug output is now:

---------------------------------------

2017-07-24 09:23:53,083 DEBUG urllib3.connectionpool._new_conn: Starting new HTTP connection (1): 134.130.3.96
2017-07-24 09:23:53,085 DEBUG urllib3.connectionpool._make_request: http://134.130.3.96:8082 "GET /api HTTP/1.1" 404 0
Traceback (most recent call last):
  File "test-smc-api.py", line 15, in <module>
    session.login(url='http://134.130.X.Y:8082', api_key='mykey', api_version='6.2.1')
  File "/usr/local/lib/python2.7/dist-packages/smc/api/session.py", line 177, in login
    self._api_version = get_api_version(url, api_version, timeout, verify)
  File "/usr/local/lib/python2.7/dist-packages/smc/api/session.py", line 315, in get_api_version
    versions = available_api_versions(base_url, timeout, verify)
  File "/usr/local/lib/python2.7/dist-packages/smc/api/session.py", line 298, in available_api_versions
    j = json.loads(r.text)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

---------------------------------------

Do I have to restart the SMC on my server? That's what I did not ...

Best regards, Jens

Am 21.07.2017 um 15:59 schrieb David LePage:
> Hi Jens,
> This appears to be related to the initial API version discovery and the response being returned.
> Based on the messages the response data is not what was expected and cannot be serialized.
> Could you attempt to enable debug logging on the smc-python side by adding the following to your script:
> 
> ```
> import logging
> logging.getLogger()
> logging.basicConfig(
>         level=logging.DEBUG, format='%(asctime)s %(levelname)s %(name)s.%(funcName)s: %(message)s')
> ```
> 
> Also, how is the SMC information being provided to the login session? The simplest and quickest way would be to insert this into your script. You can then move this to either environment variables or config file as well but this can help make it easier initially:
> ```
> from smc import session
> 
> session.login(url='http://1.1.1.1:8082', api_key='xxxxxxxxxxxxxxxxx')
> ....do stuff....
> session.logout()
> ```
> 
> One last question, which version of SMC are you using?
> 


-- 
Dipl.-Phys. Jens Hektor, Networks
IT Center, RWTH Aachen University
Room 2.04, Wendlingweg 10, 52074 Aachen (Germany)
Phone: +49 241 80 29206 - Fax: +49 241 80 22100
http://www.itc.rwth-aachen.de - hektor@itc.rwth-aachen.de

**Comment by gabstopper** [comment]
Hi Jens,
It looks like the call to the base API entry point /api is giving a 404, not authorized. There are a couple things to check.
Within SMC, right click Management Server and SMC API tab and make sure the API service is set to Enable (box checked).
If that is the case, on the OS you could check to see if you see a service port listening:
``netstat -na | grep 8082``.

If this is running then it appears the service has not initialized, you will have to restart the Management Server service via /etc/init.d/sgMgtServer stop && /etc/init.d/sgMgtServer start.

Please let me know how that goes. I will also add some additional error handling for HTTP based errors during connection when no json is returned as is the case here.

One last note, providing api_version is optional unless you may want to force a specific version - otherwise smc-python will always use the latest version available for that version of SMC. 

You can also see available SMC versions by doing an unauthenticated fetch against <smc>:8082/api or use the helper function smc.api.session.available_api_versions:

```
print(available_api_versions('http://1.1.1.1:8082'))
[5.1, 6.1, 6.2]
```
The version in use will also display in the INFO output during connection:

2017-07-24 09:00:43,318 DEBUG smc.api.session.get_entry_points: Successfully retrieved API entry points from SMC
2017-07-24 09:00:43,319 DEBUG requests.packages.urllib3.connectionpool._new_conn: Starting new HTTP connection (1): 1.1.1.1
2017-07-24 09:00:43,378 DEBUG requests.packages.urllib3.connectionpool._make_request: http://1.1.1.1:8082 "POST /6.2/login HTTP/1.1" 200 0
2017-07-24 09:00:43,379 INFO smc.api.session.login: Using SMC API version: 6.2

**Comment by jenhek** [comment]
Hi David,

thank you for your help.

Am 24.07.2017 um 16:08 schrieb David LePage:
> It looks like the call to the base API entry point /api is giving a 404, not authorized. There are a couple things to check.
> Within SMC, right click Management Server and SMC API tab and make sure the API service is set to Enable (box checked).

The SMC tells me, that my API client I have defined for testing is in the status "offline".

But offcourse, it is enabled.

> If that is the case, on the OS you could check to see if you see a service port listening:
> ``netstat -na | grep 8082``.

This is running:

tcp        0      0 ::ffff:134.130.X.Y:8082   :::*                        LISTEN


> If this is running then it appears the service has not initialized, you will have to restart the Management Server service via /etc/init.d/sgMgtServer stop && /etc/init.d/sgMgtServer start.

Did that, too. Changed nothing.

Still a "404". When this is resolved, I guess everything should run.

Any hint where to look further?

Best regards, Jens

-- 
Dipl.-Phys. Jens Hektor, Networks
IT Center, RWTH Aachen University
Room 2.04, Wendlingweg 10, 52074 Aachen (Germany)
Phone: +49 241 80 29206 - Fax: +49 241 80 22100
http://www.itc.rwth-aachen.de - hektor@itc.rwth-aachen.de

**Comment by jenhek** [comment]
Grr. I toggled enable/disable after removing all necessary frpm the config, and now it works.

Maybe the hostname was not so good in the SMC API tab.

Thank you again for the support.

Am 25.07.2017 um 08:54 schrieb Jens Hektor:
> Hi David,
> 
> thank you for your help.
> 
> Am 24.07.2017 um 16:08 schrieb David LePage:
>> It looks like the call to the base API entry point /api is giving a 404, not authorized. There are a couple things to check.
>> Within SMC, right click Management Server and SMC API tab and make sure the API service is set to Enable (box checked).
> 
> The SMC tells me, that my API client I have defined for testing is in the status "offline".
> 
> But offcourse, it is enabled.
> 
>> If that is the case, on the OS you could check to see if you see a service port listening:
>> ``netstat -na | grep 8082``.
> 
> This is running:
> 
> tcp        0      0 ::ffff:134.130.X.Y:8082   :::*                        LISTEN
> 
> 
>> If this is running then it appears the service has not initialized, you will have to restart the Management Server service via /etc/init.d/sgMgtServer stop && /etc/init.d/sgMgtServer start.
> 
> Did that, too. Changed nothing.
> 
> Still a "404". When this is resolved, I guess everything should run.
> 
> Any hint where to look further?
> 
> Best regards, Jens
> 


-- 
Dipl.-Phys. Jens Hektor, Networks
IT Center, RWTH Aachen University
Room 2.04, Wendlingweg 10, 52074 Aachen (Germany)
Phone: +49 241 80 29206 - Fax: +49 241 80 22100
http://www.itc.rwth-aachen.de - hektor@itc.rwth-aachen.de

**Comment by gabstopper** [comment]
Ok glad it's working now. Usually the SMC is particular about being able to resolve either shortname or fqdn when referencing itself in those fields. The same applies to the Web Portal server, i.e. if you use a hostname/shortname, you must also access it the same way. Anyways, i'll close this, let me know if you have any other questions!
