### ISSUE TITLE
Change DHCP Relay IP on Interface

### ISSUE THREAD

**Issue by goots86** [gabstopper/smc-python#62]
Dear Team,

I need to know the way, if it's possible, to change DHCP Relay IP on Interface ?

THis task need to be delegated to the support in my company, but I don't want to give acess to SMC.

Thanks a lot for your answer.

**Comment by gabstopper** [comment]
Hi,
Could you elaborate on the request? You want to set DHCP Relay on a specific interface? Do you possibly have a screen shot of an example from within SMC?

**Comment by gabstopper** [comment]
Just to confirm, DHCP Relay is set on an interface in this configuration (see screenshot):

![image](https://user-images.githubusercontent.com/14811349/60763155-fe325b00-a033-11e9-988b-f91a2da36e50.png)

Just to clarify - the reference to a DHCPRelay on the interface will an element which would have to either exist or be created.
I will post an example but yes this is possible.

**Comment by gabstopper** [comment]
Based on my screen shot above, to change the IP address of a DHCP Server that is set on an interface, you could do this:

```
# Find all DHCP Server objects
for element in Search.objects.entry_point('dhcp_server'):
    if element.name == 'mydhcp_server': # Find the assigned DHCP by name
        element.update(address='3.3.3.3') # Update the address
```

**Comment by goots86** [comment]
Thanks David, it's exactly that I mean to do !
