### ISSUE TITLE
Unable to acces to Endpoint to endpoint configuration of VPN Profile

### ISSUE THREAD

**Issue by ad1rie1** [gabstopper/smc-python#63]
Hello, 

I want to modify the endpoint to endpoint tunnel : 
![image](https://user-images.githubusercontent.com/1949622/61221371-acb35b80-a718-11e9-92e5-1f4464b81a55.png)

how i can do this  ?

Dears

**Comment by ad1rie1** [comment]
Hello, any news  ?

**Comment by ad1rie1** [comment]
Duplicate of #39

**Comment by gabstopper** [comment]
Hi,
I will check out internal request tracker as this hasn't yet been possible
in SMC API.
I slated for a release, I will verify and be back.

**Comment by ad1rie1** [comment]
ok thank you :)

**Comment by ad1rie1** [comment]
i have a result for endpoint to endpoint api : 
See the API reference guide from page 27 onward: https://www.websense.com/content/support/library/ngfw/v66/rfrnce/ngfw_660_rg_smc-api_a_en-us.pdf 

Take the example Endpoint-Endpoint JSON results from page 29: 

{ 
"enabled":true, 
"endpoint_1":"http://localhost:8082/6.6/elements/fw_cluster/1554/internal_gateway/55/ 
internal_endpoint/106", 
"endpoint_2":"http://localhost:8082/6.6/elements/fw_cluster/1563/internal_gateway/59/ 
internal_endpoint/114", 
"key":0, 
"link":[ 
{ 
"href":"http://localhost:8082/6.6/elements/vpn/5/tunnels/ADcAOw==/endpoints/AGoAcg==", 
"rel":"self", 
"type":"gateway_endpoint_tunnel" 
} 
] 
} 

You can't see the vpn_profile here because it hasn't been overridden at this level. It will actually inherit it from its Gateway-Gateway tunnel. If the Gateway-Gateway tunnel has also no vpn_profile, that means it inherits it from the vpn element itself. 

So, to override the inherited profile for this Endpoint-Endpoint tunnel in this example, you would: 
1) GET http://localhost:8082/6.6/elements/vpn_profile to find the ID of the desired profile, let's pretend the profile ID is 10 
2) PUT http://localhost:8082/6.6/elements/vpn/5/tunnels/ADcAOw==/endpoints/AGoAcg== (the link to the endpoint-endpoint tunnel) with following payload where you have added the vpn_profile property: 

{ 
"enabled":true, 
"endpoint_1":"http://localhost:8082/6.6/elements/fw_cluster/1554/internal_gateway/55/ 
internal_endpoint/106", 
"endpoint_2":"http://localhost:8082/6.6/elements/fw_cluster/1563/internal_gateway/59/ 
internal_endpoint/114", 
"key":0, 
"link":[ 
{ 
"href":"http://localhost:8082/6.6/elements/vpn/5/tunnels/ADcAOw==/endpoints/AGoAcg==", 
"rel":"self", 
"type":"gateway_endpoint_tunnel", 
"vpn_profile": "http://localhost:8082/6.6/elements/vpn_profile/10" <<<--- this line added 
} 
] 
} 

3) And finally save the VPN by doing POST http://localhost:8082/6.6/elements/vpn/5/save 

Best regards,
