### ISSUE TITLE
Websocket Fail smc-monitoring

### ISSUE THREAD

**Issue by ad1rie1** [gabstopper/smc-python#73]
Hello, 

I execute fetch VPNsa in my script, it's working on dev machine but in prod i have one websocket error : 
Traceback (most recent call last):
  File "CheckSDWAN.py", line 52, in <module>
    for records in query.fetch_as_element():
  File "/usr/local/lib/python3.6/site-packages/smc_monitoring/monitors/vpns.py", line 82, in fetch_as_element
    for list_of_results in clone.fetch_raw(**kw):
  File "/usr/local/lib/python3.6/site-packages/smc_monitoring/models/query.py", line 285, in fetch_raw
    with SMCSocketProtocol(self, **self.sockopt) as protocol:
  File "/usr/local/lib/python3.6/site-packages/smc_monitoring/wsocket.py", line 118, in __enter__
    cookie=session.session_id)
  File "/usr/local/lib/python3.6/site-packages/websocket/_core.py", line 226, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "/usr/local/lib/python3.6/site-packages/websocket/_handshake.py", line 79, in handshake
    status, resp = _get_resp_headers(sock)
  File "/usr/local/lib/python3.6/site-packages/websocket/_handshake.py", line 160, in _get_resp_headers
    raise WebSocketBadStatusException("Handshake status %d %s", status, status_message, resp_headers)
websocket._exceptions.WebSocketBadStatusException: Handshake status 503 Service Unavailable

Do you know this error ?

**Comment by gabstopper** [comment]
This is odd - it seems that the service is not responding. An HTTP 503 tends to mean that the service is temporarily unavailable. This could happen if it is overloaded at the time of the request. Can you try again and see if the same error occurs? I have implemented 503 retries in smc-python but the websocket side may need this implementation. I haven't seen this specifically yet.
Please let me know if retrying works.

**Comment by ad1rie1** [comment]
I have find the main source of the issue. i have set environement variable for ignore proxy for host to all with "*". The websocket module do not read it correctly. i have to set the HTTP_proxy variable to none fot make it working ;)

**Comment by gabstopper** [comment]
Hi,
Thanks for the feedback. Do you have an example of the configuration you needed to implement to work around this? I will be sure to add this to the documentation. I believe something similar might already exist on the smc-python session doc page, please see here: https://smc-python.readthedocs.io/en/latest/pages/session.html

**Comment by ad1rie1** [comment]
The main problem is here : 
https://github.com/websocket-client/websocket-client/blob/df275d351f9887fba2774e2e1aa79ff1e5a24bd1/websocket/_url.py

In the function def _is_no_proxy_host(hostname, no_proxy): Line 103

it doesn't reconise the "*" symbol.

So, to do the job in case of no proxy, unset the environement variable directly in python with : 
os.environ['no_proxy'] = '*'
os.environ['http_proxy'] = ''
