### ISSUE TITLE
Cannot add Two objects with different name and same value into source or destination of IPV4 Access rule

### ISSUE THREAD

**Issue by MinaGithuub** [gabstopper/smc-python#79]
Hello All,
I cannot add Two address objects that have different name with same value into source or destination of IPV4 Access rule, however Forcepoint SMC accept doing the same manually via GUI .
when I tried to filter both objects before sending them as parameters to IPV4 Access rule Creation, SMC API always takes the object with bigger name convention even if the value is different.

For example:
access rule has source addresses :
name=10.1.1.0, value 10.1.1.0/24
name=N-10.1.1.0 value 10.1.1.0/24

It always gives me an error when I create access rule" smc.api.exceptions.CreateRuleFailed: Impossible to store the sub element  our-Rule. Database problem. Failed to read XML change for: id=Id[53,96,1],name=[Our_Policy],state=RESTORED"

when I remove one of these objects from the input configuration file of the other vendor Firewall, I can migrate access rule successfully to SMC.

Any solution!!!

**Comment by gabstopper** [comment]
This sounds like an SMC API version issue possibly - it's clearly having a problem saving that payload to the DB. If you are using this repo specifically, I would go to our official github page which has a more current better supported version of this library by Forcepoint directly: https://github.com/Forcepoint/fp-NGFW-SMC-python

**Comment by MinaGithuub** [comment]
Thanks you so much.
fp-NGFW-SMC-python solved the issue.
